using Cale.BuildingBlocks.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Cale.Modules.GameShow.Infrastructure.Persistence;

/// <summary>
/// Idempotent create of GameShowPacks when EF migrations are off in production.
/// </summary>
public static class GameShowPackSchemaGuard
{
    public static async Task EnsureAsync(
        CaleDbContext db,
        ILogger? logger = null,
        CancellationToken ct = default)
    {
        if (!db.Database.IsRelational())
        {
            return;
        }

        try
        {
            if (db.Database.IsNpgsql())
            {
                await db.Database.ExecuteSqlRawAsync(
                    """
                    CREATE TABLE IF NOT EXISTS "GameShowPacks" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "OwnerUserId" integer NOT NULL,
                        "SchoolUserId" integer NULL,
                        "Name" character varying(200) NOT NULL,
                        "Notes" character varying(500) NULL,
                        "PayloadJson" text NOT NULL,
                        "RoundCount" integer NOT NULL,
                        "CreatedAt" timestamp with time zone NOT NULL,
                        "UpdatedAt" timestamp with time zone NOT NULL
                    );
                    CREATE INDEX IF NOT EXISTS "IX_GameShowPacks_OwnerUserId" ON "GameShowPacks" ("OwnerUserId");
                    CREATE INDEX IF NOT EXISTS "IX_GameShowPacks_SchoolUserId" ON "GameShowPacks" ("SchoolUserId");
                    CREATE INDEX IF NOT EXISTS "IX_GameShowPacks_UpdatedAt" ON "GameShowPacks" ("UpdatedAt");
                    """,
                    ct);
            }
            else if (db.Database.IsSqlServer())
            {
                await db.Database.ExecuteSqlRawAsync(
                    """
                    IF OBJECT_ID(N'dbo.GameShowPacks', N'U') IS NULL
                    BEGIN
                        CREATE TABLE dbo.GameShowPacks (
                            Id int IDENTITY(1,1) NOT NULL PRIMARY KEY,
                            OwnerUserId int NOT NULL,
                            SchoolUserId int NULL,
                            Name nvarchar(200) NOT NULL,
                            Notes nvarchar(500) NULL,
                            PayloadJson nvarchar(max) NOT NULL,
                            RoundCount int NOT NULL,
                            CreatedAt datetimeoffset NOT NULL,
                            UpdatedAt datetimeoffset NOT NULL
                        );
                        CREATE INDEX IX_GameShowPacks_OwnerUserId ON dbo.GameShowPacks (OwnerUserId);
                        CREATE INDEX IX_GameShowPacks_SchoolUserId ON dbo.GameShowPacks (SchoolUserId);
                        CREATE INDEX IX_GameShowPacks_UpdatedAt ON dbo.GameShowPacks (UpdatedAt);
                    END
                    """,
                    ct);
            }

            logger?.LogInformation("GameShowPackSchemaGuard applied.");
        }
        catch (Exception ex)
        {
            logger?.LogWarning(ex, "GameShowPackSchemaGuard failed (non-fatal).");
        }
    }
}
