# Genera los bancos CALE (Movilidad segura, El vehículo y Actitudes) en src/Cale.Api/SeedData.
# Preguntas de redacción propia basadas en el Manual de referencia para la conducción de vehículos (ANSV, 2026).
# Uso: python tools/build_cale_banks.py
import json
import os
import random

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "Cale.Api", "SeedData")
MANUAL = "ANSV, Manual de referencia para la conducción de vehículos (2026)"
MC = "Seleccion multiple"
ATTITUDE = "Actitud"
SCALE = ["Muy en desacuerdo", "En desacuerdo", "De acuerdo", "Muy de acuerdo"]

MOV = "Movilidad segura y sostenible"
VEH = "El vehículo"

SUB = {
    # Movilidad segura y sostenible
    "concepto": ("Seguridad vial y Sistema Seguro", "Concepto de seguridad vial"),
    "enfoque": ("Seguridad vial y Sistema Seguro", "Enfoque de Sistema Seguro"),
    "compartida": ("Seguridad vial y Sistema Seguro", "Responsabilidad compartida"),
    "vias": ("Seguridad vial y Sistema Seguro", "Vías, vehículos y velocidades seguras"),
    "vision": ("Seguridad vial y Sistema Seguro", "Visión Cero: ninguna muerte en la vía es aceptable"),
    "tolerancia": ("Seguridad vial y Sistema Seguro", "Tolerancia del cuerpo humano al impacto"),
    "velocidad": ("Factores de riesgo", "Velocidad como factor de riesgo"),
    "alcohol": ("Factores de riesgo", "Alcohol y sustancias psicoactivas"),
    "fatiga": ("Factores de riesgo", "Fatiga y sueño"),
    "celular": ("Factores de riesgo", "Distracciones y uso del celular"),
    "emociones": ("Factores de riesgo", "Estrés y emociones"),
    "agresiva": ("Factores de riesgo", "Conducción agresiva"),
    "confianza": ("Factores de riesgo", "Exceso de confianza"),
    "presion": ("Factores de riesgo", "Presión social"),
    "clima": ("Factores de riesgo", "Condiciones climáticas"),
    "autocontrol": ("Comportamiento del conductor", "Autocontrol"),
    "decisiones": ("Comportamiento del conductor", "Toma de decisiones"),
    "percepcion": ("Comportamiento del conductor", "Percepción del riesgo"),
    "anticipacion": ("Comportamiento del conductor", "Anticipación"),
    "respeto": ("Comportamiento del conductor", "Respeto por los demás actores"),
    "defensiva": ("Comportamiento del conductor", "Conducción defensiva"),
    "conflictos": ("Comportamiento del conductor", "Manejo de situaciones conflictivas"),
    "individual": ("Comportamiento del conductor", "Responsabilidad individual"),
    "peatones": ("Actores viales vulnerables", "Peatones"),
    "ciclistas": ("Actores viales vulnerables", "Ciclistas"),
    "motos": ("Actores viales vulnerables", "Motociclistas"),
    "ninos": ("Actores viales vulnerables", "Niños"),
    "mayores": ("Actores viales vulnerables", "Personas mayores"),
    "discapacidad": ("Actores viales vulnerables", "Personas con discapacidad"),
    "animales": ("Actores viales vulnerables", "Animales en la vía"),
    "victimas": ("Emergencias y siniestros viales", "Víctimas y consecuencias de los siniestros"),
    "pas": ("Emergencias y siniestros viales", "Protocolo PAS: proteger, avisar y socorrer"),
    "proteger": ("Emergencias y siniestros viales", "Proteger la escena y los riesgos secundarios"),
    "avisar": ("Emergencias y siniestros viales", "Llamada a emergencias y datos que se informan"),
    "limites": ("Emergencias y siniestros viales", "Qué no debe hacer quien no está capacitado"),
    "nomover": ("Emergencias y siniestros viales", "No mover lesionados sin necesidad"),
    "sostenible": ("Movilidad sostenible", "Movilidad sostenible y movilidad activa"),
    "publico": ("Movilidad sostenible", "Transporte público y movilidad compartida"),
    "uso": ("Movilidad sostenible", "Uso responsable del vehículo"),
    "eficiente": ("Movilidad sostenible", "Conducción eficiente, consumo y emisiones"),
    # El vehículo
    "sistemas": ("Conocimiento general del vehículo", "Motor, transmisión, dirección, suspensión y frenos"),
    "carroceria": ("Conocimiento general del vehículo", "Sistema eléctrico, carrocería e instrumentación"),
    "recorrido": ("Revisión preoperacional", "Estado general, luces, espejos, vidrios, bocina y placas"),
    "fugas_cint": ("Revisión preoperacional", "Fugas y cinturones"),
    "llantas": ("Llantas", "Presión, desgaste, labrado y daños"),
    "repuesto": ("Llantas", "Llanta de repuesto y riesgo de baja presión"),
    "reventon": ("Llantas", "Reventón"),
    "frenos": ("Sistema de frenos", "Freno de servicio, de estacionamiento, pastillas y líquido"),
    "abs": ("Sistema de frenos", "ABS y señales de falla"),
    "fluidos": ("Motor y fluidos", "Aceite, refrigerante, combustible y sobrecalentamiento"),
    "fuga": ("Motor y fluidos", "Cómo reconocer una fuga"),
    "bateria": ("Sistema eléctrico y electrónico", "Batería, alternador, fusibles y arranque"),
    "testigos": ("Sistema eléctrico y electrónico", "Testigos del tablero"),
    "asistencias": ("Seguridad activa", "ABS, estabilidad, tracción y asistencia de frenado"),
    "luces": ("Seguridad activa", "Iluminación y neumáticos"),
    "ocupantes": ("Seguridad pasiva", "Cinturón, airbag, apoyacabezas y sillas infantiles"),
    "casco": ("Seguridad pasiva", "Casco en motocicleta"),
    "diario": ("Mantenimiento preventivo", "Qué revisar antes de salir"),
    "periodico": ("Mantenimiento preventivo", "Mantenimiento y revisión técnico-mecánica"),
    "decision": ("Averías e inmovilización", "Cuándo continuar y cuándo detenerse"),
    "escena": ("Averías e inmovilización", "Proteger la escena con el equipo de carretera"),
}

# (subtema, dificultad, página del manual, situación y enunciado, correcta, [incorrectas], explicación)
MOVILIDAD = [
    ("concepto", "Baja", 19,
     "Un aspirante pregunta qué competencias necesita un conductor idóneo. ¿Cuál de estas hace parte de las cinco que propone el manual de la ANSV?",
     "Valorar el riesgo y la vulnerabilidad en la movilidad.",
     ["Dominar la conducción a alta velocidad.", "Conocer de memoria todos los modelos de vehículos."],
     "Las cinco competencias son: comprender el entorno, moverse de manera idónea, valorar el riesgo y la vulnerabilidad, asumir la regulación y ser corresponsable."),
    ("concepto", "Baja", 20,
     "En una clase se discute para qué sirve la movilidad segura y sostenible. ¿Cuál es su propósito?",
     "Que todas las personas se desplacen sin poner en riesgo su vida, con comportamientos responsables y cuidando el ambiente.",
     ["Que los vehículos lleguen más rápido aunque el riesgo aumente.", "Que solo los conductores profesionales cumplan las normas."],
     "La movilidad segura y sostenible reduce el riesgo de siniestros, promueve la responsabilidad y considera el impacto en el ambiente y la comunidad."),
    ("vision", "Baja", 20,
     "Un compañero afirma que los siniestros viales son cuestión de mala suerte y siempre van a ocurrir. Según el enfoque Visión Cero, ¿qué es lo correcto?",
     "Todas las muertes y lesiones graves en el tránsito son evitables.",
     ["Un número pequeño de muertes es aceptable si el tráfico fluye.", "Solo se pueden evitar los siniestros que ocurren en carretera."],
     "Visión Cero parte de una postura ética: ninguna muerte en la vía es aceptable y todas pueden evitarse."),
    ("enfoque", "Media", 20,
     "Una alcaldía quiere aplicar el Enfoque de Sistema Seguro. ¿Qué debe gestionar de forma integral?",
     "La infraestructura, los vehículos, las velocidades y los usuarios.",
     ["Solo las multas y los comparendos.", "Únicamente el estado del pavimento."],
     "El Sistema Seguro combina vías, vehículos, velocidades y usuarios seguros para que un error humano no termine en muerte."),
    ("compartida", "Media", 20,
     "Carlos cree que la seguridad vial depende solo de las autoridades de tránsito. ¿Qué plantea el manual?",
     "Que cada usuario cumple un papel fundamental para prevenir los riesgos, junto con quienes gestionan las vías y los vehículos.",
     ["Que la responsabilidad es solo de los agentes de tránsito.", "Que la responsabilidad recae únicamente en los peatones."],
     "La seguridad vial es corresponsable: los usuarios deben reconocer su rol en la prevención del riesgo."),
    ("tolerancia", "Media", 43,
     "Dos carros iguales chocan contra un muro: uno a 30 km/h y otro a 60 km/h. ¿Por qué el segundo choque es mucho más grave?",
     "Porque la fuerza del impacto crece con la velocidad y el cuerpo humano tiene un límite para resistirla.",
     ["Porque a más velocidad los frenos dejan de funcionar.", "No es más grave: la gravedad depende solo del tamaño del vehículo."],
     "La gravedad del impacto aumenta con la masa y la velocidad; por eso la velocidad determina la severidad de las lesiones."),
    ("vias", "Media", 43,
     "En una vía con límite de 60 km/h está lloviendo y hay muchos peatones. Según la ANSV, ¿cuál es la velocidad adecuada?",
     "Una velocidad dentro del límite que además se ajuste a la lluvia, al entorno y a la presencia de peatones.",
     ["Exactamente 60 km/h, porque es lo que permite la señal.", "La misma del resto del tráfico, aunque supere el límite."],
     "La velocidad adecuada respeta el límite y se adapta a la vía, el clima, el entorno y los demás actores, considerando el error humano."),
    ("velocidad", "Media", 43,
     "Un conductor acelera en una avenida para llegar a tiempo. ¿Qué le pasa a su campo visual cuando aumenta la velocidad?",
     "Se reduce, y con él la capacidad de reaccionar ante imprevistos.",
     ["Se amplía porque el conductor se concentra más.", "No cambia, la vista funciona igual a cualquier velocidad."],
     "A mayor velocidad, menor campo visual y menos tiempo para percibir y reaccionar."),
    ("velocidad", "Alta", 44,
     "Según el Observatorio Nacional de Seguridad Vial, entre 2017 y 2020, ¿qué actor vial fue la mayoría de los fallecidos en siniestros por exceso de velocidad?",
     "Los motociclistas, cerca de 7 de cada 10.",
     ["Los peatones, más de la mitad.", "Los ocupantes de buses y busetas."],
     "Aproximadamente 7 de cada 10 fallecidos por exceso de velocidad fueron motociclistas."),
    ("velocidad", "Alta", 43,
     "Según la Organización Mundial de la Salud, citada en el manual, ¿qué proporción de las víctimas de siniestros en el mundo se relaciona con velocidad excesiva o inadecuada?",
     "Una de cada tres víctimas.",
     ["Una de cada cien víctimas.", "Casi ninguna; la velocidad influye poco."],
     "La velocidad excesiva o inadecuada aporta una de cada tres víctimas de siniestros viales en el mundo."),
    ("alcohol", "Baja", 38,
     "Andrea va a ir en su carro a una celebración donde habrá licor. ¿Cuál es la decisión más segura?",
     "Planear el regreso desde antes: designar un conductor elegido o no llevar el vehículo.",
     ["Tomar poco y esperar media hora antes de manejar.", "Tomar café al final para contrarrestar el alcohol."],
     "El manual recomienda planear con anticipación el regreso cuando hay licor, porque tener el carro a mano invita a conducir."),
    ("alcohol", "Media", 38,
     "En un control, a un conductor le hacen la prueba de alcohol. ¿Desde qué nivel lo sanciona la Ley 1696 de 2013?",
     "Desde 20 mg de etanol por 100 ml de sangre, más o menos lo que deja una cerveza.",
     ["Desde 50 mg, como en otros países.", "Solo si no puede caminar en línea recta."],
     "En Colombia hay cero tolerancia: desde 20 mg/100 ml el conductor es sancionado según la Ley 1696 de 2013."),
    ("alcohol", "Alta", 39,
     "Un conductor da 120 mg de etanol por 100 ml de sangre. ¿Qué tipo de sanción le corresponde según la Ley 1696 de 2013?",
     "Las del rango de 100 a 149 mg: suspensión de la licencia desde 5 años, multa, acciones comunitarias e inmovilización.",
     ["Solo un llamado de atención, porque no supera los 150 mg.", "Una multa pequeña, sin suspensión de la licencia."],
     "La ley escala las sanciones por rangos (20-39, 40-99, 100-149 y 150 mg en adelante); entre 100 y 149 mg la suspensión parte de 5 años."),
    ("alcohol", "Media", 40,
     "¿Qué efecto de la cocaína sobre la conducción describe el manual?",
     "Vuelve al conductor competitivo e impulsivo y le hace sobrevalorar sus capacidades.",
     ["Mejora los reflejos y la concentración.", "No afecta si se consumió unas horas antes."],
     "La cocaína aumenta la impulsividad y la sensación de dominio, lo que lleva a asumir más riesgos y cometer infracciones."),
    ("alcohol", "Media", 40,
     "¿Cuál es un efecto de la marihuana que hace peligrosa la conducción?",
     "Altera la percepción del tiempo, el espacio y la velocidad, y aumenta el tiempo de reacción.",
     ["Mejora la visión nocturna.", "Reduce el sueño y aumenta la atención."],
     "La marihuana distorsiona la noción de distancias y velocidades, dificulta la concentración y produce somnolencia."),
    ("alcohol", "Media", 41,
     "Julián toma un antihistamínico para la alergia que le da sueño. ¿Qué debe hacer antes de conducir?",
     "Consultar a un profesional: algunos antihistamínicos producen un riesgo comparable al de conducir bajo los efectos del alcohol.",
     ["Manejar normal, porque los medicamentos con fórmula no afectan.", "Tomarlo con una bebida energizante para no dormirse."],
     "Algunos antihistamínicos convencionales equivalen a conducir con alcohol en la sangre; nunca deben mezclarse con licor u otros medicamentos."),
    ("fatiga", "Baja", 36,
     "Después de tres horas al volante, Diana bosteza, parpadea seguido y cambia mucho de posición. ¿Qué debe hacer?",
     "Detenerse en un lugar seguro y descansar.",
     ["Subir el volumen de la música y abrir la ventana.", "Tomar una bebida energizante y seguir."],
     "Son signos de fatiga que pueden llevar a microsueños; lo único seguro es parar y descansar."),
    ("fatiga", "Media", 37,
     "Va a hacer un viaje largo por carretera. ¿Cada cuánto recomienda el manual hacer una pausa activa?",
     "Cada 2 horas o 200 km, con una pausa de al menos 15 minutos.",
     ["Cada 5 horas, con una pausa de 5 minutos.", "Solo cuando aparezca el sueño."],
     "En trayectos de más de dos horas o 200 km, el conductor debería hacer pausas activas de por lo menos 15 minutos."),
    ("fatiga", "Baja", 36,
     "Pedro planea un viaje de ocho horas. ¿Qué recomienda el manual sobre la comida?",
     "Planear dónde y cuándo comer, sin comer mientras maneja y evitando una sola comida muy abundante.",
     ["Comer mientras conduce para no perder tiempo.", "Hacer una sola comida grande antes de salir y no parar."],
     "Las comidas abundantes producen somnolencia y pesadez; comer manejando reduce la atención."),
    ("celular", "Alta", 37,
     "Laura va a 60 km/h y baja la mirada 10 segundos para leer un mensaje. ¿Cuántos metros recorre aproximadamente sin mirar la vía?",
     "Unos 167 metros.",
     ["Unos 20 metros.", "Unos 60 metros."],
     "A 60 km/h se recorren cerca de 16,7 metros por segundo; en 10 segundos son unos 167 metros a ciegas."),
    ("celular", "Baja", 34,
     "Un motociclista quiere escuchar música con audífonos mientras conduce. ¿Qué indica el manual?",
     "Debe evitarlo, porque los audífonos disminuyen la atención y la percepción del entorno.",
     ["Es recomendable porque reduce el estrés.", "Solo está mal si va por carretera."],
     "El manual pide evitar celulares, pantallas y audífonos que disminuyan la atención, especialmente en motocicleta."),
    ("emociones", "Media", 32,
     "Un conductor sale muy estresado de una discusión. ¿Por qué el manual recomienda no conducir así?",
     "Porque el estrés severo es un factor de riesgo y además aumenta el consumo de combustible.",
     ["Porque el estrés hace que el carro pierda potencia.", "No hay relación entre el estrés y la conducción."],
     "Estar sometido a mucho estrés aumenta el riesgo de siniestro y lleva a una conducción menos eficiente."),
    ("agresiva", "Baja", 27,
     "Otro conductor le cierra el paso de forma brusca. ¿Qué indica el manejo preventivo?",
     "No responder con agresión, ni por provocación ni por venganza, y mantener la distancia.",
     ["Pitarle y seguirlo para reclamarle.", "Cerrarle el paso más adelante para que aprenda."],
     "Una de las reglas del manejo preventivo es no agredir a los demás, ni por provocación ni por venganza."),
    ("confianza", "Media", 38,
     "Un conductor ha manejado varias veces después de beber sin que le pase nada. ¿Qué advierte el manual sobre esa experiencia?",
     "Le crea una falsa sensación de control que aumenta su riesgo.",
     ["Demuestra que tiene tolerancia y puede seguir haciéndolo.", "Significa que su cuerpo elimina el alcohol más rápido."],
     "Haber conducido bebido sin consecuencias genera una percepción equivocada del riesgo."),
    ("presion", "Baja", 35,
     "Sus amigos le insisten en ir más rápido porque van tarde a un concierto. ¿Cuál es la actitud responsable?",
     "Mantener una velocidad segura: la decisión no cambia por la presión del grupo.",
     ["Acelerar un poco para no quedar mal.", "Dejar que otro maneje aunque haya tomado."],
     "En ninguna circunstancia se debe poner una vida en riesgo; la prisa de otros no justifica una conducta insegura."),
    ("clima", "Media", 26,
     "Conduce de noche por una carretera con niebla espesa. ¿Qué luces debe usar?",
     "Las luces medias, y las exploradoras junto con ellas si el vehículo las tiene.",
     ["Las luces altas, porque alumbran más lejos.", "Solo las luces de posición para no encandilar."],
     "Las luces altas rebotan en las gotas de la niebla como en un espejo; las medias se proyectan al piso y se ven mejor."),
    ("clima", "Media", 26,
     "En una vía de montaña soplan vientos laterales muy fuertes. ¿Qué recomienda el manual, sobre todo en motocicleta?",
     "Reducir la velocidad y sujetar con firmeza el volante o el manubrio, corrigiendo con suavidad.",
     ["Acelerar para pasar rápido la zona de viento.", "Aflojar el manubrio para que la moto se acomode sola."],
     "Con viento fuerte, a menor velocidad el vehículo se afirma mejor y es más fácil corregir la trayectoria."),
    ("clima", "Baja", 25,
     "¿Entre qué horas indica el manual que deben ir encendidas las luces medias, además de cuando hay mala visibilidad?",
     "Entre las 18:00 y las 6:00 del día siguiente.",
     ["Entre las 20:00 y las 4:00.", "Solo cuando ya está completamente oscuro."],
     "Las luces medias se usan entre la puesta y la salida del sol (18:00 a 6:00) y cuando la visibilidad es adversa: sirven para ver y ser visto."),
    ("percepcion", "Media", 25,
     "De noche se acerca un vehículo en sentido contrario y usted lleva las luces altas. ¿Cuándo debe cambiar a las medias?",
     "Antes de quedar a 150 metros o menos del otro vehículo.",
     ["Cuando esté a unos 20 metros.", "No hace falta cambiarlas si la vía es recta."],
     "No se deben usar luces altas a 150 metros o menos de los vehículos que se aproximan, porque encandilan."),
    ("percepcion", "Baja", 25,
     "Sale de un parqueadero muy iluminado a una vía oscura. ¿Qué recomienda el manual?",
     "Conducir despacio hasta que los ojos se adapten a la oscuridad.",
     ["Encender las luces altas aunque haya otros vehículos.", "Acelerar para salir rápido de la zona oscura."],
     "Al pasar de la luz a la oscuridad la vista tarda en adaptarse, así que se debe reducir la velocidad."),
    ("percepcion", "Media", 24,
     "Antes de iniciar un viaje, ¿qué debe evaluar el conductor según el enfoque de gestión del riesgo?",
     "Su estado físico y emocional, su atención, el vehículo, el entorno y el clima.",
     ["Solo el nivel de combustible.", "Únicamente que lleve los documentos."],
     "Conducir implica gestionar el riesgo: identificar, evaluar y anticipar situaciones peligrosas antes y durante el viaje."),
    ("anticipacion", "Media", 91,
     "Para evitar frenadas y giros de último momento, ¿hasta dónde recomienda el manual mirar hacia adelante?",
     "Al menos una cuadra en la ciudad y unos 400 metros en carretera.",
     ["Solo hasta el vehículo de adelante.", "Unos 10 metros, en cualquier vía."],
     "Mirar lejos permite anticiparse, frenar con tiempo, ahorrar combustible y contaminar menos."),
    ("anticipacion", "Baja", 27,
     "Tiene la luz verde y se acerca a un cruce. ¿Qué indica el manejo preventivo?",
     "Observar a los demás y no suponer que le van a dar el paso.",
     ["Cruzar sin mirar, porque tiene la prelación.", "Acelerar para pasar antes de que cambie."],
     "Aunque tenga derecho de paso, el conductor preventivo observa la circulación de los demás."),
    ("defensiva", "Baja", 24,
     "¿En qué consiste la conducción preventiva o defensiva?",
     "En conducir atento y anticiparse a los posibles errores de los demás.",
     ["En reaccionar con firmeza cuando otro se equivoca.", "En circular siempre por el carril izquierdo."],
     "El manejo preventivo siempre ofrece una alternativa frente a la maniobra peligrosa de otros."),
    ("defensiva", "Media", 24,
     "Va detrás de otro vehículo a unos 50 km/h, en el mismo carril. Según el artículo 108 del Código Nacional de Tránsito, ¿qué distancia mínima debe mantener?",
     "20 metros.",
     ["10 metros.", "5 metros."],
     "Art. 108: hasta 30 km/h, 10 m; de 30 a 60 km/h, 20 m; de 60 a 80 km/h, 25 m; más de 80 km/h, 30 m."),
    ("defensiva", "Media", 24,
     "En carretera va a 90 km/h detrás de un camión. ¿Qué separación mínima exige el artículo 108 del Código?",
     "30 metros, o la que indique la autoridad.",
     ["15 metros.", "25 metros."],
     "Desde 80 km/h en adelante, la separación mínima es de 30 metros o la que indique la autoridad competente."),
    ("defensiva", "Media", 25,
     "Va a 30 km/h y empieza a llover fuerte. ¿Qué hace con la distancia de seguridad?",
     "La aumenta por encima de los 10 metros, porque el piso mojado alarga el frenado.",
     ["La mantiene en 10 metros, porque es lo que dice la norma.", "La reduce para no perder de vista al de adelante."],
     "La distancia del art. 108 es un mínimo: la humedad, la visibilidad y el peso obligan a aumentarla."),
    ("decisiones", "Media", 32,
     "En carretera quiere adelantar a un camión, pero también quiere ahorrar combustible. ¿Qué debe primar?",
     "La seguridad: solo adelanta con espacio suficiente, aunque gaste más combustible.",
     ["El ahorro: adelanta sin acelerar mucho, aunque tarde más en el carril contrario.", "Adelantar en una curva, donde el camión va más despacio."],
     "Al adelantar o en una emergencia la seguridad está por encima de la economía."),
    ("autocontrol", "Baja", 47,
     "Un peatón baja de repente a la calzada por un sitio indebido. ¿Cuál es la reacción correcta?",
     "Respetar el límite y darle prelación, sin acercar el vehículo de forma agresiva para darle una lección.",
     ["Acercarse rápido y pitarle para que aprenda.", "Mantener la velocidad, porque él está incumpliendo."],
     "Aunque el peatón se equivoque, el conductor no debe intimidarlo: la vida está primero."),
    ("conflictos", "Baja", 27,
     "En un trancón, otro conductor le grita e insulta. ¿Qué es lo adecuado?",
     "No responder, mantener la calma y alejarse de la situación si es necesario.",
     ["Bajarse del carro a reclamarle.", "Responderle con la bocina hasta que se calle."],
     "El manejo preventivo pide no agredir a otros ni por provocación ni por venganza."),
    ("individual", "Baja", 33,
     "Un conductor se pone el cinturón y baja la velocidad solo cuando ve agentes de tránsito. ¿Qué dice el manual de esa conducta?",
     "Es nociva: las normas deben cumplirse por autorregulación, haya o no autoridad.",
     ["Es suficiente, porque las multas solo las ponen los agentes.", "Es correcta si la vía está vacía."],
     "Cuando las normas no se asumen de forma autónoma, la persona queda desprotegida y pone en peligro a los demás."),
    ("individual", "Media", 34,
     "Según el estudio de la ANSV sobre causas probables de siniestros, ¿qué factor está asociado a más del 90 % de los casos?",
     "El comportamiento humano.",
     ["El mal estado de las vías.", "Las fallas mecánicas."],
     "Irrespetar los límites, desobedecer las señales, conducir embriagado o ir en contravía son conductas humanas."),
    ("respeto", "Baja", 45,
     "Un conductor estaciona sobre el andén porque solo se demora cinco minutos. ¿Por qué es peligroso?",
     "Porque obliga a los peatones a bajar a la calzada y los expone a ser atropellados.",
     ["Porque se pueden dañar las llantas.", "No es peligroso si es por poco tiempo."],
     "Estacionar en el andén traslada el riesgo al peatón, que debe caminar por la vía."),
    ("peatones", "Baja", 47,
     "Pasa cerca de un paradero donde hay un bus detenido. ¿Qué debe hacer?",
     "Reducir la velocidad y estar listo para detenerse, porque puede salir un peatón por delante o por detrás del bus.",
     ["Pitar para avisar y seguir a la misma velocidad.", "Adelantar rápido al bus antes de que arranque."],
     "Cerca de los paraderos los peatones aparecen de forma sorpresiva o corren para alcanzar el bus."),
    ("peatones", "Media", 47,
     "Va por el carril izquierdo y en el derecho un carro se detiene antes de una cebra. ¿Qué hace?",
     "Disminuye la velocidad y se prepara para detenerse, porque puede haber un peatón cruzando que no ve.",
     ["Lo adelanta, porque su carril está libre.", "Le pita para que el otro carro avance."],
     "Nunca adelante a un vehículo detenido ante un paso peatonal: puede ocultar a alguien que cruza."),
    ("peatones", "Baja", 48,
     "De madrugada, cerca de una zona de bares, un peatón ebrio camina por la calzada. ¿Qué es lo correcto?",
     "Reducir la velocidad y darle espacio: es preferible perder unos segundos que atropellarlo.",
     ["Pitar fuerte y pasar cerca para que se aparte.", "Mantener la velocidad, porque él está incumpliendo."],
     "El manual pide especial atención con personas ebrias en zonas de bares, sobre todo de noche y los fines de semana."),
    ("peatones", "Baja", 48,
     "Conduce por una calle comercial muy concurrida, cerca de un colegio y de paraderos. ¿Qué velocidad máxima recuerda el manual para estas zonas?",
     "30 km/h.",
     ["50 km/h.", "60 km/h."],
     "En calles comerciales, zonas residenciales, cerca de colegios y paraderos no se deben superar los 30 km/h."),
    ("ciclistas", "Baja", 50,
     "Va a adelantar a un ciclista en una subida. ¿Qué espacio lateral mínimo recomienda el manual?",
     "Al menos 1,5 metros.",
     ["50 centímetros.", "Basta con no tocarlo."],
     "El ciclista puede tambalearse por el viento o el esfuerzo en subida; por eso se deja al menos 1,5 m."),
    ("ciclistas", "Media", 50,
     "Va detrás de un ciclista y quiere girar a la derecha en el siguiente cruce. ¿Qué debe hacer?",
     "No adelantarlo antes ni en el cruce: espera a que pase la intersección y luego gira.",
     ["Adelantarlo rápido y girar delante de él.", "Pitarle para que se detenga y lo deje girar."],
     "Adelantar a un ciclista justo antes de girar a la derecha es una de las causas típicas de atropello."),
    ("motos", "Media", 74,
     "Un conductor de carro no entiende por qué las motos deben llevar las luces encendidas de día. ¿Cuál es la razón?",
     "La moto es un vehículo angosto y poco visible; con las luces encendidas los demás la detectan antes.",
     ["Para que la batería se cargue mejor.", "Es solo una costumbre, no lo exige la norma."],
     "El artículo 96 del Código exige a las motos circular con luces encendidas para aumentar su visibilidad."),
    ("ninos", "Baja", 49,
     "Un balón sale rodando a la calle entre carros estacionados. ¿Qué debe anticipar?",
     "Que un niño puede salir detrás del balón: reduce la velocidad y se prepara para frenar.",
     ["Nada; solo debe esquivar el balón.", "Que debe pitar para que nadie salga."],
     "La presencia de niños es una señal de alerta: el conductor debe anticiparse a su comportamiento espontáneo."),
    ("ninos", "Baja", 50,
     "Pasa junto a un bus escolar detenido. ¿Qué precaución aplica?",
     "Pasar despacio y atento, porque pueden subir, bajar o cruzar niños por delante o por detrás.",
     ["Adelantarlo rápido para no quedar detrás.", "Pitar para que los niños esperen en el andén."],
     "Los niños pueden aparecer de forma imprevista alrededor de un vehículo escolar detenido."),
    ("mayores", "Baja", 49,
     "Un adulto mayor cruza lentamente y su semáforo está por cambiar a verde. ¿Qué hace?",
     "Espera a que termine de cruzar, porque las personas mayores necesitan más tiempo y calculan peor la velocidad de los vehículos.",
     ["Avanza despacio para presionarlo a que se apure.", "Le pita para que se dé cuenta del cambio."],
     "Las personas mayores tienen menor movilidad y reacciones más lentas; siempre se les cede el paso."),
    ("discapacidad", "Baja", 48,
     "Un peatón con bastón blanco empieza a cruzar la calle. ¿Qué exige el manual?",
     "Detenerse por completo y cederle el paso.",
     ["Reducir un poco y pasar por detrás de él.", "Pitar para que sepa que viene un vehículo."],
     "Ante un peatón con discapacidad visual que cruza con bastón, los vehículos deben parar completamente."),
    ("animales", "Baja", 35,
     "En una vía rural ve un caballo suelto cerca de la calzada. ¿Qué es lo correcto?",
     "Reducir la velocidad y estar listo para detenerse, sin asustar al animal.",
     ["Pasar rápido antes de que se mueva.", "Pitar fuerte para que se aleje de la vía."],
     "Los animales también son actores vulnerables y sus movimientos son impredecibles."),
    ("victimas", "Media", 23,
     "Una víctima de un siniestro debe ser trasladada en ambulancia a la clínica más cercana. ¿Quién cubre ese traslado?",
     "El SOAT.",
     ["La víctima, con su EPS.", "La autoridad de tránsito."],
     "El traslado de las víctimas a la institución de salud adecuada tiene cobertura del SOAT."),
    ("victimas", "Baja", 23,
     "Un herido en un siniestro no tiene afiliación a salud ni dinero. ¿Lo deben atender en urgencias?",
     "Sí: la atención de urgencias es obligatoria para toda persona, sin importar su capacidad de pago.",
     ["Solo si tiene EPS.", "Solo si alguien paga un depósito."],
     "Todos los hospitales y clínicas están obligados a brindar atención de urgencias, incluidas las ambulancias."),
    ("pas", "Baja", 22,
     "Es el primero en llegar a un choque con heridos. ¿En qué orden debe actuar según el protocolo PAS?",
     "Proteger, avisar y socorrer.",
     ["Socorrer, avisar y proteger.", "Avisar, socorrer y proteger."],
     "PAS significa proteger, avisar y socorrer, en ese orden."),
    ("proteger", "Media", 23,
     "¿Qué significa proteger dentro del protocolo PAS?",
     "Ubicarse en un lugar seguro, evaluar los riesgos y señalizar la escena para evitar otro siniestro.",
     ["Sacar de inmediato a los heridos de los vehículos.", "Tomar fotos de los daños para el seguro."],
     "Proteger busca que nadie más resulte herido, incluido quien ayuda."),
    ("avisar", "Media", 23,
     "Ocurre un siniestro en una carretera nacional. ¿Qué números de emergencia indica el manual?",
     "El #767 en carretera y el 123 en las ciudades.",
     ["El 911 en cualquier lugar.", "El 112 en carretera y el 132 en ciudad."],
     "En ciudades se llama al NUSE 123 y en carretera al #767."),
    ("avisar", "Baja", 23,
     "Llama a la línea de emergencias para reportar un siniestro. ¿Qué información debe dar?",
     "Dónde está, con un punto de referencia, y su número de teléfono; luego sigue las instrucciones del operador.",
     ["Solo su nombre, y cuelga rápido para no ocupar la línea.", "La placa de su vehículo y nada más."],
     "Una ubicación precisa y un número de contacto permiten que la ayuda llegue rápido."),
    ("limites", "Media", 23,
     "No tiene formación en primeros auxilios y encuentra a un herido consciente. ¿Qué es lo correcto?",
     "Acompañarlo y tranquilizarlo, ayudando solo dentro de su capacidad y sin causarle más daño.",
     ["Darle agua y moverlo para que quede cómodo.", "Quitarle el casco de inmediato si es motociclista."],
     "Socorrer es hacer contacto con la víctima y ayudar según la propia capacidad, sin causar daño adicional."),
    ("nomover", "Media", 23,
     "¿Cuándo se justifica mover a un lesionado antes de que llegue la ayuda?",
     "Solo si corre un peligro inmediato, como fuego o el riesgo de otro choque.",
     ["Siempre, para llevarlo rápido al hospital en un carro particular.", "Cuando se queja de dolor."],
     "Mover a un lesionado puede agravar sus heridas; el traslado debe hacerlo una ambulancia."),
    ("sostenible", "Baja", 21,
     "¿Cuál de estas acciones contribuye a una movilidad sostenible según el manual?",
     "Usar el transporte público, la bicicleta o compartir el carro.",
     ["Usar el carro particular para cada trayecto corto.", "Dejar el motor encendido durante los trancones largos."],
     "El manual menciona el transporte público, la bicicleta, la caminata y el carro compartido como estrategias de mitigación."),
    ("sostenible", "Media", 21,
     "¿Por qué la movilidad sostenible también debe ser segura?",
     "Porque promover la bicicleta o la caminata sin planeación ni educación puede aumentar las lesiones y muertes.",
     ["Porque los vehículos eléctricos no necesitan frenos.", "No tiene relación: lo sostenible ya es seguro."],
     "La movilidad debe ser al mismo tiempo ambientalmente sostenible y segura."),
    ("publico", "Baja", 21,
     "Cuatro compañeros de trabajo viven en el mismo barrio. ¿Por qué compartir un carro (carpooling) ayuda al ambiente?",
     "Porque se movilizan más personas en menos vehículos y se reducen las emisiones.",
     ["Porque el carro compartido no necesita revisión técnico-mecánica.", "Porque permite exceder el límite de velocidad."],
     "El carro compartido es una acción de mitigación de la contaminación mencionada en el manual."),
    ("eficiente", "Baja", 28,
     "¿Cuánto combustible puede ahorrarse al aplicar las técnicas de conducción eficiente?",
     "Entre un 10 % y un 15 %.",
     ["Menos del 1 %.", "Más del 50 %."],
     "Optimizar la forma de conducir permite ahorrar entre un 10 % y un 15 % de combustible."),
    ("eficiente", "Baja", 32,
     "Una obra lo obliga a detenerse varios minutos. ¿Qué es lo más eficiente?",
     "Apagar el motor, porque en detenciones de más de un minuto conviene hacerlo.",
     ["Dejarlo encendido, porque encenderlo gasta más.", "Acelerar en neutro para que no se apague."],
     "En detenciones de más de un minuto es más económico apagar el motor; en un semáforo en rojo normalmente no conviene."),
    ("eficiente", "Media", 32,
     "Ve a lo lejos un semáforo en rojo. ¿Qué técnica de conducción eficiente aplica?",
     "Soltar el acelerador con anticipación y reducir con el cambio puesto, sin pasar a neutro.",
     ["Seguir acelerando y frenar fuerte al final.", "Pasar a neutro y dejar rodar el vehículo."],
     "Reducir con el cambio engranado corta la inyección de combustible y mejora la capacidad de frenado."),
    ("eficiente", "Media", 30,
     "Sus llantas tienen 5 PSI menos de la presión recomendada. ¿Qué efecto tiene sobre el consumo?",
     "Lo aumenta cerca de un 3 %.",
     ["No tiene ningún efecto.", "Lo reduce, porque la llanta se agarra mejor."],
     "Una llanta desinflada exige más trabajo; además empeora la adherencia y la maniobrabilidad."),
    ("eficiente", "Baja", 31,
     "Al encender un carro moderno, ¿qué recomienda la conducción eficiente?",
     "No pisar el acelerador.",
     ["Acelerar varias veces para calentarlo.", "Mantenerlo acelerado durante dos minutos."],
     "Los vehículos modernos regulan electrónicamente la inyección al arrancar; acelerar solo aumenta el consumo."),
    ("uso", "Baja", 29,
     "Un conductor lleva siempre en el baúl una caja de herramientas pesada y un portaequipajes en el techo que casi no usa. ¿Qué efecto tiene?",
     "Aumenta el consumo de combustible: cada kilo cuenta.",
     ["Mejora la estabilidad y reduce el consumo.", "Ninguno, el peso no influye."],
     "Mientras más peso lleva el vehículo, más energía necesita para moverse."),
    ("uso", "Baja", 29,
     "Tiene que hacer tres diligencias en distintos puntos de la ciudad. ¿Qué hábito de uso responsable del vehículo aplica?",
     "Planear la ruta y hacer todas las diligencias en un solo viaje.",
     ["Hacer un viaje por cada diligencia para no cansarse.", "Buscar la ruta en el celular mientras maneja."],
     "La eficiencia es hacer lo mismo gastando menos: planear la ruta evita kilómetros y viajes innecesarios."),
]

VEHICULO = [
    ("diario", "Baja", 65,
     "Antes de salir de viaje, ¿qué cinco componentes recomienda el manual revisar en cualquier vehículo motorizado?",
     "Los líquidos, los frenos, el sistema eléctrico, las llantas y los espejos.",
     ["El radio, el aire acondicionado, la tapicería, los rines y la pintura.", "Solo el combustible y el aceite."],
     "Esos cinco componentes aplican a todo vehículo; la moto suma el kit de arrastre."),
    ("diario", "Baja", 65,
     "Si el vehículo es una motocicleta, ¿qué debe revisar además de los cinco componentes básicos?",
     "El kit de arrastre (cadena, piñón y corona).",
     ["El nivel del líquido limpiaparabrisas.", "El perno rey y la quinta rueda."],
     "En motocicleta el kit de arrastre transmite la fuerza a la rueda y su falla puede bloquearla."),
    ("recorrido", "Baja", 65,
     "Va a hacer la revisión preoperacional de su vehículo. ¿Cómo debe estar el motor?",
     "Apagado.",
     ["Encendido y acelerado.", "Encendido, con el vehículo en movimiento lento."],
     "Los componentes de la revisión preoperacional se revisan con el vehículo apagado."),
    ("recorrido", "Baja", 65,
     "Un conductor dice que no hace la revisión preoperacional porque tarda mucho. ¿Cuánto toma según el manual?",
     "No más de diez minutos.",
     ["Al menos una hora.", "Medio día en un taller."],
     "La revisión toma unos diez minutos y puede ayudar a prevenir un siniestro."),
    ("recorrido", "Media", 65,
     "Conduce un bus de pasajeros. Además de los componentes básicos, ¿qué debe verificar?",
     "La carrocería, el funcionamiento de las puertas, los limpiabrisas y el líquido limpiaparabrisas.",
     ["Solo que el radio funcione.", "La quinta rueda y el perno rey."],
     "En vehículos de cuatro o más ruedas, sobre todo de pasajeros, se revisan también carrocería, puertas y limpiabrisas."),
    ("decision", "Baja", 65,
     "Durante la revisión preoperacional encuentra que el pedal del freno se hunde más de lo normal. ¿Qué recomienda el manual?",
     "No usar el vehículo hasta corregir la falla en un servicio técnico especializado.",
     ["Salir con cuidado y revisarlo después del viaje.", "Usar solo el freno de mano durante el recorrido."],
     "Si encuentra una anomalía, lo mejor es abstenerse de usar el vehículo hasta solucionarla."),
    ("asistencias", "Baja", 66,
     "¿Qué son los sistemas de seguridad activa de un vehículo?",
     "Los que ayudan a evitar que ocurra el choque, como los frenos, las luces, la dirección y la suspensión.",
     ["Los que reducen las lesiones cuando el choque ya ocurrió, como el airbag.", "Los que avisan a la aseguradora después del choque."],
     "La seguridad activa previene el choque; la pasiva reduce sus consecuencias."),
    ("ocupantes", "Baja", 80,
     "¿Cuál de estos es un elemento de seguridad pasiva?",
     "El cinturón de seguridad.",
     ["El sistema de frenos ABS.", "Las luces direccionales."],
     "La seguridad pasiva minimiza los efectos de un choque: cinturón, sillas infantiles, apoyacabezas, airbags y habitáculo."),
    ("asistencias", "Media", 66,
     "Un vendedor le dice que el carro tiene control de estabilidad. ¿Para qué sirve?",
     "Combina el frenado y la dirección para estabilizar el vehículo y prevenir volcamientos.",
     ["Mantiene una velocidad fija en carretera.", "Avisa cuando falta aceite."],
     "El control de estabilidad articula varios sistemas para neutralizar fuerzas que sacarían al vehículo de su trayectoria."),
    ("abs", "Media", 67,
     "Debe frenar de emergencia en un carro con ABS. ¿Qué ventaja le da este sistema?",
     "Evita que las ruedas se bloqueen y le permite seguir dirigiendo el vehículo.",
     ["Hace que el carro frene siempre en la mitad de la distancia.", "Apaga el motor automáticamente."],
     "El ABS impide el bloqueo de las ruedas en una frenada fuerte, por lo que el conductor conserva el control de la dirección."),
    ("abs", "Alta", 67,
     "Su carro no tiene ABS y debe frenar de emergencia. ¿Qué técnica describe el manual para que las ruedas no se bloqueen?",
     "Aplicar y soltar rápidamente la presión sobre el pedal.",
     ["Pisar el freno a fondo y mantenerlo sin soltar.", "Halar el freno de mano con fuerza."],
     "Sin ABS, las ruedas bloqueadas hacen que el vehículo siga recto; por eso se dosifica la presión. Es difícil de dominar, por lo que se prefieren vehículos con ABS."),
    ("testigos", "Media", 67,
     "Al encender el carro, el testigo del ABS se prende un momento y luego se apaga. ¿Qué significa?",
     "Es normal: el sistema hace su verificación al arrancar.",
     ["Que el ABS está dañado y no debe conducir.", "Que se acabó el líquido de frenos."],
     "Normalmente el ABS solo se nota por la verificación del testigo al encender el motor."),
    ("sistemas", "Media", 68,
     "¿Por qué los vehículos modernos tienen frenos de dos circuitos?",
     "Para que, si falla un circuito, el otro conserve parte de la capacidad de frenado.",
     ["Para frenar el doble de rápido en cualquier situación.", "Para que el freno de mano funcione solo."],
     "Con un solo circuito, una fuga dejaría sin frenos todas las ruedas; con dos se mantiene cierto efecto de frenado."),
    ("frenos", "Media", 68,
     "Acaba de pasar por un charco profundo y siente que los frenos responden menos. ¿Qué hace?",
     "Frena varias veces con firmeza, verificando que nadie venga detrás, para secarlos.",
     ["Sigue igual, se secan solos con la velocidad.", "Acelera fuerte para calentarlos."],
     "El agua entre los elementos de fricción reduce el frenado; se elimina frenando varias veces con presión."),
    ("frenos", "Baja", 68,
     "¿Cómo funciona por lo general el freno de estacionamiento y cuándo se usa?",
     "Es mecánico, suele actuar sobre las ruedas traseras y debe usarse siempre que se detenga.",
     ["Es hidráulico y solo se usa en pendientes muy fuertes.", "Actúa sobre las cuatro ruedas y se usa para frenar en marcha."],
     "Aunque su uso continuo exige ajustes periódicos, el manual recomienda usarlo siempre que se detenga."),
    ("frenos", "Media", 68,
     "Completa el líquido de frenos hasta la marca MAX, pero a los pocos días vuelve a estar bajo. ¿Qué significa?",
     "Que hay una pérdida y debe ir de inmediato a un taller especializado.",
     ["Que es normal, el líquido se evapora con el calor.", "Que debe cambiar a un aceite de motor más espeso."],
     "El depósito no debería perder volumen; si sigue bajando, hay una falla que debe revisar un técnico."),
    ("periodico", "Media", 68,
     "Va a mover un carro que lleva más de seis meses guardado. ¿Qué recomienda el manual?",
     "Hacer revisar todo el sistema de frenos antes de moverlo.",
     ["Solo inflar las llantas.", "Arrancar y probar los frenos a alta velocidad."],
     "Tras seis meses quieto, cilindros, tuberías, pastillas o bandas y líquido deben revisarse antes de circular."),
    ("luces", "Baja", 72,
     "¿Cuándo deben usarse las luces intermitentes de emergencia (luces de parqueo)?",
     "Cuando el vehículo está detenido por una falla o para advertir un peligro adelante, nunca como excusa para estacionar mal.",
     ["Para estacionar un momento en un sitio prohibido.", "Siempre que llueva, mientras se circula."],
     "Las intermitentes avisan una obstrucción o un peligro; no autorizan un estacionamiento prohibido."),
    ("recorrido", "Baja", 70,
     "Va a cambiar los bombillos de las direccionales. ¿De qué color recomienda el manual que sean?",
     "Amarillos o ámbar, para que no se confundan con las luces de freno.",
     ["Rojos, para que se vean más.", "Azules, porque llaman más la atención."],
     "Los demás conductores perciben más rápido las direccionales ámbar y no las confunden con el frenado."),
    ("luces", "Alta", 70,
     "Quiere comprobar que sus luces medias no encandilan a los demás. ¿Qué prueba describe el manual?",
     "Estacionar a 10 metros de una pared y verificar que el haz no quede más alto que el centro de los faros.",
     ["Encenderlas de día y mirar si se ven desde lejos.", "Pedir a otro conductor que le haga cambio de luces."],
     "Un mal ajuste puede encandilar a otros o hacer que vea los obstáculos cuando ya los tiene encima."),
    ("luces", "Media", 72,
     "Un conductor maneja de noche solo con las exploradoras encendidas. ¿Por qué es un error?",
     "Porque las exploradoras son auxiliares: iluminan una franja corta y deben usarse junto con las luces medias.",
     ["No es un error, las exploradoras alumbran más que las medias.", "Porque las exploradoras gastan más gasolina."],
     "Sin las luces de servicio, el conductor solo verá un objeto cuando ya esté encima de él."),
    ("luces", "Baja", 74,
     "Según el artículo 96 del Código Nacional de Tránsito, ¿cuándo debe un motociclista llevar las luces encendidas?",
     "Todo el tiempo que circule por vías públicas, de día y de noche.",
     ["Solo de noche.", "Solo en carretera o cuando llueve."],
     "La motocicleta es un vehículo angosto que necesita aumentar su visibilidad."),
    ("luces", "Media", 71,
     "Hace un viaje nocturno con el baúl muy cargado. ¿Qué pasa con los faros y qué debe hacer?",
     "Apuntan más arriba de lo normal; debe ajustar su altura con el mando del tablero.",
     ["Apuntan más abajo; debe usar luces altas todo el viaje.", "Nada cambia con la carga."],
     "Con la parte trasera cargada la trompa se levanta y los faros pueden encandilar a los demás."),
    ("carroceria", "Media", 71,
     "¿Para qué sirven los catadióptricos (retrorreflectores) rojos de la parte trasera?",
     "Reflejan las luces de otros vehículos y hacen visible el suyo aunque sus luces fallen.",
     ["Iluminan la placa por la noche.", "Son solo un adorno de la carrocería."],
     "No tienen luz propia: reflejan la de quien se aproxima. Por eso no se deben quitar ni cambiar por piezas sin ellos."),
    ("carroceria", "Baja", 85,
     "¿Cuál de estos elementos está prohibido en un vehículo particular?",
     "Luces rojas o azules de emergencia.",
     ["Un extintor.", "Una linterna."],
     "Las luces rojas o azules son de uso exclusivo de vehículos de emergencia y de policía."),
    ("carroceria", "Media", 85,
     "Un conductor quiere instalar luces exploradoras en la parte trasera de su camioneta y un televisor a la vista. ¿Qué dice la norma?",
     "Ambos están prohibidos.",
     ["Ambos están permitidos si los instala un taller.", "Solo se permite el televisor si es pequeño."],
     "Las exploradoras traseras y un televisor a la vista del conductor están en la lista de equipos no permitidos."),
    ("sistemas", "Media", 75,
     "Mueve el volante y las ruedas tardan en responder, como con retraso. ¿Qué indica?",
     "Juego en la dirección: un desgaste que puede llevar incluso al desprendimiento de una llanta.",
     ["Que la dirección está bien lubricada.", "Que la presión de las llantas es la correcta."],
     "No debe haber juego en el volante; si lo hay, la dirección necesita revisión."),
    ("sistemas", "Media", 75,
     "En una vía plana y despejada, a baja velocidad, suelta un momento el volante y el carro se va hacia un lado. ¿Qué indica?",
     "Una posible falla en algún elemento de la dirección, que debe revisarse.",
     ["Que la vía está inclinada y es normal.", "Que el motor está muy revolucionado."],
     "Si el vehículo tiende a desplazarse hacia un lado, es indicio de falla y su revisión es indispensable."),
    ("fluidos", "Media", 75,
     "Al girar bruscamente, la dirección hidráulica produce un gemido. ¿Qué debe revisar?",
     "El nivel del fluido de la dirección asistida.",
     ["El nivel de agua del limpiaparabrisas.", "La presión de la llanta de repuesto."],
     "Un gemido en virajes bruscos puede indicar problemas en la dirección asistida hidráulica."),
    ("llantas", "Media", 76,
     "Revisa el labrado de sus llantas. ¿Qué profundidad recomienda el manual y cuál es el límite peligroso?",
     "Se aconseja más de 3 mm; por debajo de 1,6 mm el agarre en piso mojado es peligroso.",
     ["Basta con 0,5 mm en cualquier clima.", "Se aconseja 1 mm; por debajo de 0,3 mm es peligroso."],
     "Con poco labrado el agua no se evacúa por los surcos y aumenta el riesgo de perder el contacto con el pavimento."),
    ("llantas", "Media", 76,
     "Una llanta está gastada solo en el centro de la banda de rodamiento. ¿Qué indica?",
     "Que se usó con exceso de presión.",
     ["Que se usó con poca presión.", "Que la llanta está en perfecto estado."],
     "Desgaste en el centro: exceso de aire. Desgaste solo en los bordes: falta de aire."),
    ("llantas", "Media", 76,
     "Una llanta está gastada solo en los bordes. ¿Qué indica?",
     "Que se usó con menos presión de la recomendada.",
     ["Que se usó con exceso de presión.", "Que el vehículo nunca se ha alineado."],
     "Rodar con poca presión hace que la llanta se apoye en sus bordes y se desgaste allí."),
    ("llantas", "Baja", 76,
     "¿Cuándo y con qué frecuencia se debe medir la presión de las llantas?",
     "En frío, al menos cada 7 a 10 días.",
     ["En caliente, después de un viaje largo, una vez al año.", "Solo cuando se ve una llanta desinflada."],
     "Con la llanta caliente la lectura es inexacta; por eso se mide en frío y con frecuencia."),
    ("repuesto", "Media", 76,
     "Una llanta delantera tiene baja presión. ¿Qué efecto produce en la conducción?",
     "El vehículo tiende a irse hacia ese lado y la dirección se siente más pesada.",
     ["El vehículo frena mejor.", "No produce ningún efecto."],
     "La baja presión adelante hace la dirección más pesada y desvía el vehículo hacia el lado afectado."),
    ("llantas", "Baja", 76,
     "¿Cada cuánto recomienda el manual rotar las llantas?",
     "Cada 10.000 km.",
     ["Cada 100.000 km.", "Nunca, la rotación no es necesaria."],
     "Rotar las llantas evita un desgaste irregular y alarga su vida útil."),
    ("llantas", "Media", 77,
     "Una llanta tiene buen labrado, pero fue montada hace seis años. ¿Qué recomienda el manual?",
     "Cambiarla: hacia los cinco años el material envejece aunque la llanta tenga poco uso.",
     ["Usarla hasta que el labrado llegue a 1,6 mm.", "Ponerla como repuesto para siempre."],
     "El caucho pierde sus propiedades con el tiempo, aunque el dibujo se vea bien."),
    ("llantas", "Alta", 77,
     "En la llanta dice 205/55 R16. ¿Qué significa el número 16?",
     "El diámetro del rin, en pulgadas.",
     ["El ancho de la llanta, en centímetros.", "La presión máxima, en libras."],
     "205 es el ancho en milímetros, 55 la relación entre alto y ancho, R indica que es radial y 16 el diámetro del rin."),
    ("repuesto", "Media", 78,
     "¿Con qué presión debe guardar la llanta de repuesto?",
     "Con la presión más alta recomendada por el fabricante.",
     ["Desinflada, para que no se dañe.", "Con la mitad de la presión normal."],
     "No se sabe cuándo habrá que usarla; con la presión más alta compensa la pérdida natural de aire."),
    ("repuesto", "Media", 78,
     "Va a transportar una carga muy pesada en su camioneta. ¿Qué hace con la presión de las llantas?",
     "La aumenta según la tabla del fabricante, que está en el pilar B o en el manual del vehículo.",
     ["La disminuye para que las llantas agarren más.", "La deja igual; la carga no influye."],
     "Con carga pesada se ajusta la presión a lo que indica el fabricante para esa condición."),
    ("reventon", "Alta", 78,
     "Revienta una llanta trasera mientras conduce y la cola del vehículo se desvía. ¿Qué indica el manual?",
     "Girar el volante hacia el lado al que se desvía la parte trasera.",
     ["Girar el volante al lado contrario con fuerza.", "Frenar a fondo de inmediato."],
     "Corregir hacia el lado del derrape ayuda a recuperar la trayectoria."),
    ("reventon", "Media", 78,
     "Revienta una llanta delantera. ¿Qué debe hacer?",
     "Sostener firme el volante y frenar de forma suave.",
     ["Frenar a fondo y girar bruscamente hacia la berma.", "Soltar el volante para que el carro se acomode solo."],
     "Un frenazo o un giro brusco con una llanta delantera reventada puede hacer perder el control."),
    ("sistemas", "Media", 79,
     "Empuja hacia abajo una esquina del carro, la suelta y el vehículo sigue rebotando varias veces. ¿Qué indica?",
     "Que los amortiguadores están en mal estado y deben cambiarse.",
     ["Que la suspensión está en perfecto estado.", "Que las llantas tienen demasiado aire."],
     "Si al soltar el vehículo sigue oscilando, o se oyen chirridos, es hora de cambiar los amortiguadores."),
    ("asistencias", "Alta", 78,
     "¿Qué efecto tienen unos amortiguadores gastados sobre el frenado?",
     "Aumentan la distancia de frenado y hacen que el ABS pierda efectividad.",
     ["Mejoran el frenado porque el carro se inclina hacia adelante.", "Ninguno, solo afectan la comodidad."],
     "La suspensión mantiene las llantas en contacto con el piso; sin ese contacto el frenado y el ABS empeoran."),
    ("periodico", "Media", 79,
     "Su carro cae seguido en huecos y a veces sube andenes. ¿Cada cuánto recomienda el manual alinearlo y balancearlo?",
     "Cada dos o tres meses.",
     ["Cada cinco años.", "Solo cuando cambie de carro."],
     "La dirección se desalinea más rápido con sobrecargas, huecos y andenes; alinear y balancear evita desgaste y vibraciones."),
    ("ocupantes", "Baja", 80,
     "¿A qué altura debe ajustar el apoyacabezas?",
     "A la altura de la cabeza y cerca de ella, para prevenir el latigazo cervical.",
     ["En la posición más baja, para que no estorbe.", "A la altura del cuello, para descansar."],
     "Mal ajustado, el apoyacabezas pierde eficacia y puede ser contraproducente en un impacto trasero."),
    ("ocupantes", "Media", 81,
     "Un pasajero dice que no necesita el cinturón porque el carro tiene airbag. ¿Qué responde el manual?",
     "Que el airbag se infla a unos 300 km/h y sin cinturón puede causar lesiones graves; funcionan en conjunto.",
     ["Que tiene razón: el airbag reemplaza el cinturón.", "Que el airbag solo funciona si el cinturón está suelto."],
     "El airbag y el cinturón son un conjunto; juntos reducen cerca de un 68 % la posibilidad de muerte."),
    ("ocupantes", "Media", 87,
     "Según la Organización Mundial de la Salud, ¿cuánto reduce el cinturón de seguridad el riesgo de morir en un siniestro?",
     "Hasta un 50 %.",
     ["Menos del 5 %.", "Nada, sobrevivir depende de la suerte."],
     "El cinturón disminuye hasta en un 50 % el riesgo de pérdida de vidas en un siniestro."),
    ("ocupantes", "Media", 87,
     "Alguien afirma que en un choque es mejor salir disparado del carro. ¿Qué dice el manual?",
     "Es falso: salir expulsado multiplica el riesgo de morir; es mucho más seguro quedar dentro con el cinturón.",
     ["Es cierto, así se evita quedar atrapado.", "Solo es cierto en choques a baja velocidad."],
     "Salir expulsado aumenta mucho el riesgo de lesión de columna y de muerte."),
    ("ocupantes", "Baja", 88,
     "Una mujer embarazada pregunta si debe usar el cinturón. ¿Qué indica el manual?",
     "Sí debe usarlo, con la banda inferior por debajo del abdomen.",
     ["No debe usarlo porque es peligroso para el bebé.", "Solo debe usar la banda del hombro."],
     "El riesgo de lesión para la madre y el bebé es mayor si no lo usa."),
    ("ocupantes", "Media", 87,
     "Un conductor no usa el cinturón en trayectos cortos dentro de la ciudad. ¿Qué le diría el manual?",
     "Que cerca de la mitad de los siniestros con víctimas ocurre en zona urbana y un choque a 30 o 40 km/h puede ser mortal.",
     ["Que tiene razón, en ciudad la velocidad es baja y no pasa nada.", "Que solo es obligatorio en carretera."],
     "Usted puede ir despacio, pero otro vehículo puede venir rápido; el cinturón se usa en todos los trayectos."),
    ("ocupantes", "Baja", 106,
     "Va a llevar en su carro a su sobrina de 6 años. ¿Dónde debe viajar?",
     "En el asiento trasero, con un sistema de retención infantil adecuado a su edad y tamaño.",
     ["En el asiento delantero, con el cinturón del adulto.", "En las piernas de un adulto en el asiento trasero."],
     "Los menores de 10 años deben ir atrás y con sistemas de retención infantil."),
    ("ocupantes", "Media", 106,
     "Un niño de 7 años y 25 kg ya no cabe en su silla orientada hacia adelante. ¿Qué dispositivo corresponde?",
     "Un cojín elevador (booster), preferiblemente con respaldo, para que use bien el cinturón.",
     ["Ninguno, ya puede usar el cinturón como un adulto.", "Una silla para bebé orientada hacia atrás."],
     "El cojín elevador se recomienda entre los 4 y 12 años, de 15 a 36 kg o hasta los 135 a 150 cm de estatura."),
    ("casco", "Baja", 92,
     "¿Cuánto puede reducir el uso correcto del casco la probabilidad de morir en un siniestro?",
     "Hasta un 40 %.",
     ["Un 2 %.", "Nada, si la moto va despacio."],
     "El uso correcto del casco reduce hasta en un 40 % la probabilidad de muerte."),
    ("casco", "Media", 93,
     "Va a comprar un casco para su moto. ¿Cuál cumple lo que indica el manual?",
     "Uno certificado (por ejemplo NTC 4533, DOT o ECE 22.05), de su talla y bien abrochado.",
     ["El más económico, aunque le quede grande.", "Uno decorativo tipo gorra, porque es más fresco."],
     "El casco debe tener un estándar de calidad reconocido y ser de la talla adecuada al perímetro de la cabeza."),
    ("casco", "Media", 93,
     "¿Cómo debe quedar ajustada la correa (sistema de retención) del casco?",
     "Con más o menos un centímetro entre el cuello y la correa.",
     ["Suelta, para poder respirar mejor.", "Desabrochada en trayectos cortos."],
     "Una correa bien ajustada evita que el casco salga despedido en un choque."),
    ("escena", "Media", 83,
     "¿Cuál de estos elementos hace parte del equipo de carretera obligatorio según el artículo 30 del Código?",
     "Dos tacos para bloquear el vehículo.",
     ["Un parlante portátil.", "Un compresor de aire eléctrico."],
     "El equipo incluye gato, cruceta, dos señales reflectivas, botiquín, extintor, dos tacos, herramienta básica, llanta de repuesto y linterna."),
    ("escena", "Media", 83,
     "Un agente le pide mostrar el equipo de carretera. ¿Cuál lista corresponde a lo que exige el artículo 30 del Código?",
     "Gato, cruceta, dos señales reflectivas, botiquín, extintor, dos tacos, herramienta básica, llanta de repuesto y linterna.",
     ["Gato, cruceta, chaleco y cables de arranque, nada más.", "Botiquín y extintor solamente."],
     "Son nueve elementos mínimos para atender una emergencia en la vía."),
    ("escena", "Alta", 84,
     "Se vara en una calle residencial donde nadie debería ir a más de 30 km/h. ¿A qué distancia aproximada pone los triángulos?",
     "A unos 12 metros.",
     ["A unos 2 metros.", "A unos 100 metros."],
     "A 30 km/h un vehículo recorre unos 8 metros por segundo; 12 metros le dan cerca de segundo y medio para reaccionar."),
    ("escena", "Alta", 84,
     "Se vara en una avenida arteria donde se circula a unos 60 km/h. ¿A qué distancia aproximada pone los triángulos?",
     "A unos 24 metros.",
     ["A unos 5 metros.", "A unos 12 metros."],
     "A 60 km/h se recorren unos 16 metros por segundo; con segundo y medio de margen son unos 24 metros."),
    ("escena", "Alta", 84,
     "Se vara en una carretera donde los vehículos pasan entre 80 y 120 km/h. ¿A qué distancia aproximada pone los triángulos?",
     "A unos 44 metros o más.",
     ["A unos 12 metros.", "A unos 24 metros."],
     "A esas velocidades se recorren entre 22 y 33 metros por segundo, por lo que se toma la mayor distancia."),
    ("escena", "Media", 84,
     "Va a instalar los triángulos después de una avería. ¿Dónde y cómo los coloca?",
     "En el mismo carril del vehículo detenido, con la cara reflectiva hacia los vehículos que se acercan.",
     ["En el carril contrario, para que lo vean los que vienen de frente.", "Encima del techo del vehículo."],
     "Si tiene linterna, úsela mientras camina a instalarlos y luego entre los triángulos y el vehículo."),
    ("escena", "Media", 112,
     "María sufre una avería en una vía nacional y la reparación tomará cerca de una hora. Según el artículo 79 del Código, ¿qué debe hacer mientras repara?",
     "Poner señales visibles entre 50 y 100 metros adelante y atrás del vehículo.",
     ["Dejar un espacio de unos cinco metros adelante y atrás.", "Reparar a una distancia de entre cuatro y ocho metros de los demás vehículos."],
     "El artículo 79 fija los mínimos para hacer reparaciones de fuerza mayor en la vía pública."),
    ("decision", "Baja", 83,
     "Sufre un pinchazo en una carretera. ¿Qué hace primero?",
     "Salirse de la vía con prudencia, usando los espejos, hasta un lugar donde no quede expuesto al tráfico.",
     ["Frenar en el carril y cambiar la llanta allí mismo.", "Seguir rodando con la llanta pinchada hasta el próximo pueblo."],
     "Cambiar una llanta expuesto al tráfico lo pone en riesgo de ser atropellado."),
    ("diario", "Baja", 86,
     "Se sube a un carro prestado. ¿Cómo debe ajustar el asiento según el manual?",
     "Para pisar los pedales hasta el fondo sin moverse y alcanzar sin esfuerzo la parte de arriba del volante.",
     ["Lo más atrás posible, con los brazos estirados del todo.", "Lo más adelante posible, con el pecho pegado al volante."],
     "Una buena postura mantiene la alerta y el control; también se ajustan espejos, apoyacabezas y cinturón."),
    ("bateria", "Media", 89,
     "¿Por qué no se debe tocar la llave de encendido con el vehículo en movimiento?",
     "Porque puede bloquear el volante y hacerle perder el control.",
     ["Porque se descarga la batería.", "Porque se apagan las luces de freno."],
     "Girar la llave en marcha puede activar el bloqueo de la dirección."),
    ("sistemas", "Media", 90,
     "Va a bajar una pendiente larga en un carro mecánico. ¿Qué es lo correcto?",
     "Bajar con un cambio engranado, el mismo que usaría para subir, y nunca en neutro.",
     ["Bajar en neutro para ahorrar combustible.", "Bajar en el cambio más alto y frenar todo el tiempo."],
     "En neutro el vehículo toma tanto impulso que los frenos pueden no bastar para detenerlo."),
    ("frenos", "Media", 90,
     "¿Qué puede pasar si baja una pendiente larga usando solo el freno de servicio?",
     "Los frenos pueden sobrecalentarse y perder fuerza.",
     ["Los frenos se enfrían y frenan mejor.", "No pasa nada, los frenos están hechos para eso."],
     "Por eso se reduce la velocidad al inicio del descenso y se usa el freno de motor."),
    ("fluidos", "Media", 65,
     "La aguja de temperatura del motor sube a la zona roja mientras conduce. ¿Qué hace?",
     "Detenerse en un lugar seguro, apagar el motor y no abrir el radiador en caliente.",
     ["Seguir hasta el destino y revisar después.", "Abrir de inmediato la tapa del radiador para que se enfríe."],
     "El sobrecalentamiento puede dañar el motor; el líquido caliente a presión puede causar quemaduras graves."),
    ("fuga", "Media", 68,
     "Al mover el carro en la mañana ve una mancha de líquido en el piso donde estuvo estacionado. ¿Qué debe hacer?",
     "Identificar de qué sistema viene y, si no lo sabe, no arriesgarse y llevarlo a un taller.",
     ["Ignorarla, todos los carros botan algo de líquido.", "Echarle agua al depósito que vea más bajo."],
     "Una fuga de frenos, aceite o refrigerante puede causar una falla grave; la revisión de líquidos hace parte de la preoperacional."),
    ("fugas_cint", "Baja", 86,
     "Durante la revisión preoperacional, ¿qué debe verificar de los cinturones de seguridad?",
     "Que todos abrochen, se ajusten y no estén rotos ni deshilachados.",
     ["Solo el del conductor.", "Nada, los cinturones no hacen parte de la revisión."],
     "El cinturón puede salvar la vida y no usarlo acarrea una multa; debe funcionar en todos los puestos."),
    ("carroceria", "Media", 82,
     "¿Qué es el habitáculo o célula de supervivencia de un vehículo?",
     "La estructura rígida donde van los ocupantes, que debe mantenerse intacta en un choque.",
     ["El baúl donde se guarda el equipo de carretera.", "El compartimiento donde está el motor."],
     "Las zonas menos rígidas absorben el golpe; el habitáculo protege a los ocupantes."),
    ("sistemas", "Media", 88,
     "¿Por qué debe arrancar acelerando de forma gradual?",
     "Porque arrancar con mucha potencia puede hacer que el volante gire sin control, sobre todo en piso resbaloso.",
     ["Porque así el carro alcanza antes la velocidad máxima.", "No importa cómo arranque."],
     "Un giro brusco del conjunto motor-transmisión puede inducir giros en la dirección."),
]

# (enunciado, es_actitud_segura, explicación, dificultad)
ACTITUDES = [
    ("Si voy de afán, puedo pasarme un semáforo en amarillo acelerando.", False,
     "El amarillo indica que debe prepararse para detenerse; acelerar aumenta el riesgo de choque en el cruce.", "Baja"),
    ("Puedo conducir después de tomarme un par de cervezas si me siento bien.", False,
     "Desde 20 mg de etanol hay sanción, y sentirse bien no significa estar en condiciones de conducir.", "Baja"),
    ("Contestar un mensaje en el celular en un semáforo en rojo no tiene riesgo.", False,
     "El celular distrae aun detenido: no se percibe el cambio de luz ni a los peatones que cruzan.", "Media"),
    ("Si un peatón cruza por donde no es, está bien acercarme rápido para que aprenda.", False,
     "Intimidar a un peatón pone su vida en riesgo; siempre se le da prelación.", "Baja"),
    ("Si la calle está vacía, puedo superar el límite de velocidad.", False,
     "Los límites consideran riesgos que no siempre se ven, como peatones o niños que aparecen de repente.", "Baja"),
    ("El cinturón de seguridad solo hace falta en carretera.", False,
     "Cerca de la mitad de los siniestros con víctimas ocurre en zona urbana.", "Baja"),
    ("Si el trayecto es corto, un niño pequeño puede ir en mis piernas en el puesto delantero.", False,
     "Los menores de 10 años van atrás y con sistema de retención infantil, sin importar la distancia.", "Baja"),
    ("Cuando alguien me cierra el paso, tengo derecho a responderle de la misma forma.", False,
     "El manejo preventivo pide no agredir ni por provocación ni por venganza.", "Baja"),
    ("Si llevo prisa, puedo subirme al andén para salir del trancón.", False,
     "El andén es exclusivo de los peatones; los vehículos no pueden circular por él.", "Baja"),
    ("Las señales de tránsito son sugerencias; lo importante es la experiencia del conductor.", False,
     "Las señales reglamentarias son obligatorias y su violación acarrea sanciones.", "Media"),
    ("Si no hay agentes de tránsito cerca, no pasa nada si incumplo una norma.", False,
     "Las normas se cumplen por autorregulación, porque protegen la vida, no por miedo a la multa.", "Media"),
    ("Cuando tengo sueño, una bebida energizante basta para seguir manejando.", False,
     "Ante la fatiga lo seguro es detenerse y descansar; las bebidas estimulantes no eliminan el riesgo.", "Media"),
    ("Los ciclistas deberían andar por el andén para no estorbar a los carros.", False,
     "La bicicleta es un vehículo con derecho a la vía; el andén es de los peatones.", "Media"),
    ("Puedo adelantar en una curva si conozco bien la vía.", False,
     "En una curva no hay visibilidad del carril contrario; conocer la vía no elimina el riesgo.", "Baja"),
    ("Llevar el casco sin abrochar es suficiente en trayectos cortos.", False,
     "Un casco sin abrochar sale despedido en un choque y no protege.", "Baja"),
    ("Si mi licencia está suspendida, puedo manejar con cuidado mientras me la devuelven.", False,
     "Conducir con la licencia suspendida es una infracción grave y significa conducir sin habilitación.", "Media"),
    ("Si el SOAT se venció hace pocos días, puedo seguir circulando normalmente.", False,
     "Sin SOAT vigente no se puede circular y las víctimas quedan sin esa cobertura.", "Media"),
    ("Estacionar un momento en un espacio para personas con discapacidad no afecta a nadie.", False,
     "Esos espacios garantizan la movilidad de quien los necesita; ocuparlos lo obliga a exponerse.", "Baja"),
    ("En una discusión de tránsito es válido bajarme del carro a reclamar.", False,
     "Bajarse a reclamar escala el conflicto y expone a todos a riesgos en la vía.", "Media"),
    ("Pitar con insistencia hace que el tráfico avance más rápido.", False,
     "La bocina es para advertir un peligro; usarla sin necesidad genera estrés y conflictos.", "Media"),
    ("Llevar más pasajeros de los permitidos está bien si son familiares.", False,
     "Cada ocupante necesita su puesto y su cinturón; el parentesco no cambia el riesgo.", "Baja"),
    ("Si mis amigos me presionan para ir más rápido, debo complacerlos.", False,
     "La decisión segura no cambia por la presión del grupo.", "Baja"),
    ("Reduzco la velocidad cuando veo niños cerca de la vía, aunque no haya una señal.", True,
     "La presencia de un niño en la calle es en sí misma una señal de alerta.", "Baja"),
    ("Antes de salir reviso las llantas, los frenos y las luces.", True,
     "La revisión preoperacional toma pocos minutos y puede prevenir un siniestro.", "Baja"),
    ("Si voy a tomar alcohol, dejo el carro o designo un conductor elegido.", True,
     "Planear el regreso con anticipación evita la tentación de conducir bajo efectos del alcohol.", "Baja"),
    ("Cedo el paso a los peatones en las cebras aunque tenga prisa.", True,
     "Los peatones tienen prelación en las cebras y son los actores más vulnerables.", "Baja"),
    ("Cuando estoy cansado, prefiero detenerme a descansar.", True,
     "La fatiga produce microsueños; descansar es la única medida segura.", "Baja"),
    ("Cumplo las normas de tránsito aunque no haya autoridades presentes.", True,
     "La autorregulación protege su vida y la de los demás en todo momento.", "Baja"),
    ("Dejo al menos un metro y medio de distancia al adelantar a un ciclista.", True,
     "El ciclista puede tambalearse por el viento o el esfuerzo; 1,5 m es el espacio mínimo recomendado.", "Media"),
    ("Guardo el celular donde no lo pueda usar mientras conduzco.", True,
     "Alejar el celular elimina una de las principales distracciones al volante.", "Baja"),
    ("Si otro conductor comete un error, procuro evitar el choque en lugar de reclamarle.", True,
     "Muchos siniestros se evitan cuando alguien cubre la falta de precaución del otro.", "Media"),
    ("Uso el cinturón en todos los trayectos y pido a mis pasajeros que lo usen.", True,
     "El cinturón reduce hasta un 50 % el riesgo de morir y es obligatorio para todos los ocupantes.", "Baja"),
    ("Con lluvia o niebla aumento la distancia con el vehículo de adelante.", True,
     "El piso mojado y la baja visibilidad alargan la distancia necesaria para frenar.", "Baja"),
    ("Si presencio un siniestro, primero protejo la escena y luego pido ayuda.", True,
     "El protocolo PAS empieza por proteger para evitar más víctimas.", "Media"),
    ("Planeo mis viajes para salir con tiempo y no tener que correr.", True,
     "Salir con tiempo reduce el estrés y la tentación de exceder la velocidad.", "Baja"),
    ("Respeto los espacios reservados para personas con discapacidad.", True,
     "Esos espacios garantizan la accesibilidad de quienes más lo necesitan.", "Baja"),
]


def knowledge_bank(rows, subject, seed):
    rnd = random.Random(seed)
    questions = []
    for code, difficulty, page, text, correct, wrong, explanation in rows:
        topic, subtopic = SUB[code]
        options = [{"text": correct, "isCorrect": True}] + [{"text": w, "isCorrect": False} for w in wrong]
        rnd.shuffle(options)
        questions.append({
            "text": text,
            "type": MC,
            "subject": subject,
            "topic": topic,
            "subtopic": subtopic,
            "difficulty": difficulty,
            "explanation": explanation,
            "source": f"{MANUAL}, p. {page}. Redacción propia de Luz Verde.",
            "options": options,
        })
    return questions


def attitude_bank():
    questions = []
    for statement, safe, explanation, difficulty in ACTITUDES:
        correct = {"De acuerdo", "Muy de acuerdo"} if safe else {"Muy en desacuerdo", "En desacuerdo"}
        stance = "estar de acuerdo" if safe else "estar en desacuerdo"
        questions.append({
            "text": statement,
            "type": ATTITUDE,
            "topic": "Actitudes",
            "difficulty": difficulty,
            "explanation": f"La actitud segura es {stance}. {explanation}",
            "source": "Formato de actitudes del examen teórico (Res. 20253040037125 de 2025, citado en "
                      f"{MANUAL}, p. 112). Enunciado propio de Luz Verde.",
            "options": [{"text": s, "isCorrect": s in correct} for s in SCALE],
        })
    return questions


def write(name, payload):
    path = os.path.join(OUT, name)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"{name}: {len(payload['questions'])} preguntas")


write("banco-cale-movilidad.json", {
    "bankName": "Movilidad segura y sostenible (CALE)",
    "description": "Preguntas tipo CALE (situación + 3 opciones) de redacción propia, basadas en el Manual de referencia para la conducción de vehículos de la ANSV (2026).",
    "blockName": "Núcleo: Movilidad segura y sostenible",
    "questions": knowledge_bank(MOVILIDAD, MOV, 108),
})
write("banco-cale-vehiculo.json", {
    "bankName": "El vehículo (CALE)",
    "description": "Preguntas tipo CALE (situación + 3 opciones) de redacción propia, basadas en el Manual de referencia para la conducción de vehículos de la ANSV (2026).",
    "blockName": "Núcleo: El vehículo",
    "questions": knowledge_bank(VEHICULO, VEH, 30),
})
write("banco-cale-actitudes.json", {
    "bankName": "Actitudes del conductor (CALE)",
    "description": "Enunciados de actitudes con escala de cuatro niveles, como en el examen teórico oficial. Redacción propia de Luz Verde.",
    "blockName": "Actitudes del conductor",
    "questions": attitude_bank(),
})
