/**
 * Genera banco Normas de calidad (CEA / Ley 769).
 * Reglas:
 * - Una sola respuesta correcta, posición variada (no siempre A/B/C/D).
 * - La correcta NO es sistemáticamente la más larga ni la mejor redactada.
 * - Distractoras plausibles; explicación breve y útil.
 */
const fs = require('fs');
const path = require('path');

const OUT = path.join(
  __dirname,
  '..',
  'src',
  'Cale.Api',
  'SeedData',
  'banco-normas-transito.json'
);

const EXTRA = require('./normas_extra_v21.js');

/** @type {Array<{topic:string, difficulty:string, text:string, correct:string, wrong:[string,string,string], explanation:string, source?:string}>} */
const RAW = [
  // Circulación
  { topic: 'Circulación', difficulty: 'Media', text: 'En Colombia, por regla general, ¿por qué costado de la vía deben circular los vehículos?', correct: 'Por el costado derecho.', wrong: ['Por el costado izquierdo, como en algunos países europeos.', 'Por el centro de la calzada para tener mejor visibilidad.', 'Indistintamente, según el sentido que indique el GPS.'], explanation: 'La circulación se hace por la derecha, salvo excepciones previstas en la norma.' },
  { topic: 'Circulación', difficulty: 'Media', text: 'Si va a girar a la izquierda en una vía de doble sentido, ¿qué debe hacer antes de iniciar la maniobra?', correct: 'Señalizar con anticipación, ubicar el vehículo correctamente y ceder el paso a quien corresponda.', wrong: ['Acelerar para completar el giro antes de que lleguen otros vehículos.', 'Detenerse en el centro del cruce sin señalizar hasta que alguien le indique.', 'Girar inmediatamente si no ve peatones, sin mirar atrás.'], explanation: 'Toda maniobra exige anticipación, señalización y respeto a la prioridad.' },
  { topic: 'Circulación', difficulty: 'Alta', text: 'Circular en zig-zag entre vehículos en una vía urbana es:', correct: 'Una conducta riesgosa y sancionable.', wrong: ['Permitida si se usa el claxon continuamente.', 'Obligatoria cuando el tráfico está detenido.', 'Recomendada para mejorar el flujo vehicular.'], explanation: 'Maniobras abruptas e imprudentes ponen en riesgo a todos los actores viales.' },
  { topic: 'Circulación', difficulty: 'Media', text: 'En una calzada con varios carriles en el mismo sentido, el carril izquierdo se usa preferentemente para:', correct: 'Adelantar o circular a mayor velocidad cuando la vía lo permita.', wrong: ['Estacionar temporalmente sin apagar el motor.', 'Circular siempre a la mínima velocidad posible.', 'Uso exclusivo de motocicletas, sin excepción.'], explanation: 'Los carriles se usan según velocidad y maniobras; el izquierdo no es “carril de descanso”.' },
  { topic: 'Circulación', difficulty: 'Media', text: '¿Qué significa circular “a la defensiva”?', correct: 'Anticipar riesgos y conducir preveniendo errores propios y ajenos.', wrong: ['Ceder siempre el paso aunque se tenga prioridad legal.', 'Usar solo el claxon para advertir a los demás.', 'Circular por debajo del mínimo permitido en toda la ciudad.'], explanation: 'La conducción defensiva reduce accidentes anticipando situaciones peligrosas.' },

  // Velocidad
  { topic: 'Velocidad', difficulty: 'Media', text: 'Si no hay señalización específica, ¿cuál es el límite general de velocidad en vías urbanas para automóviles?', correct: '60 km/h.', wrong: ['80 km/h.', '40 km/h en todas las calles sin excepción.', '100 km/h si la vía es amplia.'], explanation: 'En zona urbana el límite general para automóviles es 60 km/h, salvo señalización distinta.' },
  { topic: 'Velocidad', difficulty: 'Media', text: 'En zona escolar, cuando hay señalización de límite reducido, usted debe:', correct: 'Respetar el límite indicado y extremar precaución.', wrong: ['Mantener 60 km/h porque “es el máximo urbano”.', 'Acelerar para salir rápido de la zona.', 'Detenerse siempre en mitad de la calzada.'], explanation: 'La señalización local prevalece y protege a niños y peatones.' },
  { topic: 'Velocidad', difficulty: 'Alta', text: 'Reducir la velocidad ante lluvia intensa o niebla es:', correct: 'Obligatorio por seguridad y por el deber de adaptar la conducción a las condiciones.', wrong: ['Opcional si lleva luces altas encendidas.', 'Prohibido porque atrasa el tráfico.', 'Solo necesario de noche.'], explanation: 'La velocidad segura depende del estado de la vía, visibilidad y clima.' },
  { topic: 'Velocidad', difficulty: 'Media', text: '¿Cuál es una consecuencia frecuente de exceder la velocidad?', correct: 'Mayor distancia de frenado y menor tiempo de reacción.', wrong: ['Menor consumo de combustible en todos los casos.', 'Mejor adherencia de los neumáticos.', 'Eliminación automática del riesgo de colisión.'], explanation: 'A mayor velocidad, más espacio y tiempo se necesitan para detenerse a tiempo.' },
  { topic: 'Velocidad', difficulty: 'Alta', text: 'En carretera, si la señal indica 80 km/h y usted circula a 110 km/h:', correct: 'Está infringiendo el límite y puede ser sancionado.', wrong: ['Es correcto si no hay otros vehículos cerca.', 'Solo es falta si lo detecta un radar fijo.', 'Está permitido en pendientes descendentes.'], explanation: 'El límite señalado es obligatorio independientemente de la percepción del conductor.' },

  // Prioridad e intersecciones
  { topic: 'Prioridad e intersecciones', difficulty: 'Media', text: 'En una intersección sin semáforo ni señales de “PARE” o “CEDA EL PASO”, ¿quién tiene prioridad?', correct: 'Quien llega por la derecha, en igualdad de condiciones.', wrong: ['Siempre el vehículo más grande.', 'Quien toque el claxon primero.', 'Quien circule a mayor velocidad.'], explanation: 'La regla general de prioridad es ceder a quien viene por la derecha, salvo señalización.' },
  { topic: 'Prioridad e intersecciones', difficulty: 'Media', text: 'Ante una señal de “PARE”, usted debe:', correct: 'Detenerse por completo y solo continuar cuando sea seguro.', wrong: ['Reducir un poco y seguir si no ve a nadie a simple vista.', 'Tocar el claxon y cruzar sin parar.', 'Detenerse solo si hay peatones cruzando.'], explanation: '“PARE” exige detención total, no solo disminuir la marcha.' },
  { topic: 'Prioridad e intersecciones', difficulty: 'Media', text: 'La señal “CEDA EL PASO” indica que usted debe:', correct: 'Disminuir, ceder el paso a quien tenga prioridad y continuar solo si no obliga a frenar a otros.', wrong: ['Detenerse siempre durante 10 segundos, aunque la vía esté libre.', 'Acelerar para incorporarse antes que los demás.', 'Ignorar la señal si trae prisa.'], explanation: 'Ceder el paso no siempre exige detención total, pero sí no interferir con el flujo prioritario.' },
  { topic: 'Prioridad e intersecciones', difficulty: 'Alta', text: 'Al salir de una propiedad privada a una vía pública, ¿quién tiene prioridad?', correct: 'Los vehículos y peatones que ya circulan por la vía pública.', wrong: ['Quien sale de la propiedad, porque “está incorporándose”.', 'El primero que active la direccional.', 'Solo los peatones; los vehículos no tienen prioridad.'], explanation: 'Quien se incorpora desde un predio debe ceder el paso.' },
  { topic: 'Prioridad e intersecciones', difficulty: 'Alta', text: 'En una rotonda (glorieta), la conducta correcta suele ser:', correct: 'Ceder el paso a quienes ya circulan dentro de la rotonda, salvo señalización distinta.', wrong: ['Entrar a máxima velocidad para no quedar por fuera.', 'Detenerse siempre en el centro de la rotonda.', 'Circular en sentido contrario si hay congestión.'], explanation: 'La prioridad en rotondas depende de la señalización; por regla práctica se cede a quien ya está dentro.' },

  // Semáforos
  { topic: 'Semáforos', difficulty: 'Baja', text: 'La luz roja del semáforo significa:', correct: 'Detenerse antes de la línea de parada o del cruce peatonal.', wrong: ['Avanzar con precaución a 20 km/h.', 'Detenerse solo si hay policía presente.', 'Cruzar si no hay cámaras.'], explanation: 'Rojo = alto obligatorio.' },
  { topic: 'Semáforos', difficulty: 'Media', text: 'Si el semáforo está en amarillo al aproximarse al cruce, usted debe:', correct: 'Detenerse si puede hacerlo con seguridad; si ya está muy encima, completar el cruce con precaución.', wrong: ['Acelerar siempre para “pasar en amarillo”.', 'Detenerse en mitad de la intersección.', 'Ignorar el amarillo porque no es rojo.'], explanation: 'El amarillo advierte el cambio a rojo; no es invitación a acelerar.' },
  { topic: 'Semáforos', difficulty: 'Media', text: 'Una luz intermitente amarilla en semáforo indica:', correct: 'Avanzar con precaución, cediendo el paso cuando corresponda.', wrong: ['Alto total obligatorio como luz roja fija.', 'Vía cerrada permanentemente.', 'Permiso para circular en sentido contrario.'], explanation: 'Amarillo intermitente = precaución, no libre absoluto.' },
  { topic: 'Semáforos', difficulty: 'Alta', text: 'Si el semáforo está apagado o en falla, usted debe:', correct: 'Conducir como en intersección no semaforizada: precaución y respeto a señales o prioridad.', wrong: ['Seguir como si fuera luz verde permanente.', 'Bloquear el cruce hasta que llegue un agente.', 'Usar solo el carril izquierdo.'], explanation: 'Sin semáforo operativo rigen las reglas generales de prioridad y señalización.' },
  { topic: 'Semáforos', difficulty: 'Media', text: 'Cruzar con luz roja “porque no venía nadie” es:', correct: 'Una infracción y un riesgo.', wrong: ['Permitido de madrugada.', 'Correcto si se usa direccional.', 'Válido en vías locales sin cámaras.'], explanation: 'La obligación del rojo no depende de “parecer seguro”.' },

  // Peatones
  { topic: 'Peatones y actores vulnerables', difficulty: 'Media', text: 'Ante un cruce peatonal con peatones cruzando, el conductor debe:', correct: 'Detenerse y ceder el paso a los peatones.', wrong: ['Tocar el claxon para que se apuren.', 'Pasar por detrás de ellos a baja velocidad.', 'Seguir si el semáforo vehicular está en verde, atropellándolos si no se apartan.'], explanation: 'La vida del peatón tiene prioridad en el cruce; el verde no autoriza atropellar.' },
  { topic: 'Peatones y actores vulnerables', difficulty: 'Alta', text: 'Los ciclistas en la vía deben ser tratados como:', correct: 'Usuarios legítimos de la vía a quienes se debe respetar distancia y prioridad según normas.', wrong: ['Obstáculos que pueden empujarse con el vehículo.', 'Peatones que deben ir siempre por el andén.', 'Vehículos sin derecho a circular en calzada.'], explanation: 'Ciclistas son actores viales; el conductor motor debe protegerlos.' },
  { topic: 'Peatones y actores vulnerables', difficulty: 'Media', text: 'Al adelantar a un ciclista, lo recomendable y seguro es:', correct: 'Dejar una distancia lateral generosa y solo adelantar cuando sea seguro.', wrong: ['Pasar rozando para “enseñarle” a no estorbar.', 'Tocar el claxon pegado a su rueda trasera.', 'Adelantar en curva sin visibilidad.'], explanation: 'La distancia lateral evita accidentes graves con ciclistas.' },
  { topic: 'Peatones y actores vulnerables', difficulty: 'Media', text: 'En zonas con niños jugando cerca de la vía, usted debe:', correct: 'Reducir velocidad y aumentar la atención.', wrong: ['Mantener velocidad máxima urbana.', 'Usar luces altas de día para “avisar”.', 'Acelerar para pasar rápido la zona.'], explanation: 'Los niños pueden irrumpir de forma imprevisible.' },
  { topic: 'Peatones y actores vulnerables', difficulty: 'Alta', text: 'Un vehículo de emergencia con sirena y luces debe:', correct: 'Facilitársele el paso de forma segura, sin generar otro riesgo.', wrong: ['Ser ignorado si usted tiene semáforo en verde.', 'Obligarlo a detenerse tocándole el claxon.', 'Seguirlo de cerca aprovechando su vía libre.'], explanation: 'Se cede el paso a emergencias sin maniobras peligrosas ni “colarse” detrás.' },

  // Adelantamiento
  { topic: 'Adelantamiento', difficulty: 'Media', text: 'Está prohibido adelantar, entre otros casos, cuando:', correct: 'Hay línea continua, curva sin visibilidad o señal que lo prohíbe.', wrong: ['La vía está completamente libre y con buena visibilidad.', 'Se circula en vía urbana a 30 km/h.', 'Se usa el carril derecho en recta amplia.'], explanation: 'La línea continua y la falta de visibilidad son restricciones típicas al adelantamiento.' },
  { topic: 'Adelantamiento', difficulty: 'Alta', text: 'Para adelantar de forma correcta usted debe:', correct: 'Comprobar que puede hacerlo sin peligro, señalizar y regresar al carril sin cortar al otro vehículo.', wrong: ['Adelantar por la berma si el carril está ocupado.', 'Obligar al de adelante a frenar bruscamente.', 'Adelantar a varios vehículos a la vez en curva.'], explanation: 'El adelantamiento exige visibilidad, señalización y no poner en riesgo a terceros.' },
  { topic: 'Adelantamiento', difficulty: 'Media', text: 'Si otro vehículo lo está adelantando, usted debe:', correct: 'Mantener su carril y facilitar la maniobra sin acelerar.', wrong: ['Acelerar para impedirlo.', 'Cerrar el paso moviéndose al carril izquierdo.', 'Frenar en seco en medio del adelantamiento.'], explanation: 'Colaborar con el adelantamiento seguro reduce colisiones laterales.' },
  { topic: 'Adelantamiento', difficulty: 'Alta', text: 'Adelantar por la derecha en una vía de un solo sentido con varios carriles:', correct: 'Puede ser válido según la organización de carriles, pero nunca por berma ni de forma imprudente.', wrong: ['Siempre está prohibido en cualquier circunstancia.', 'Solo lo pueden hacer buses.', 'Es obligatorio si el de adelante va lento.'], explanation: 'En vías multilcarril el “adelantar” depende del uso de carriles; la berma no es carril de avance.' },
  { topic: 'Adelantamiento', difficulty: 'Media', text: 'En un puente estrecho sin visibilidad suficiente para adelantar, lo correcto es:', correct: 'No adelantar.', wrong: ['Adelantar a máxima velocidad.', 'Usar luces altas y pasar igual.', 'Pedir por gestos que el de adelante se detenga en el puente.'], explanation: 'Sin visibilidad y espacio, adelantar es peligroso e irregular.' },

  // Estacionamiento
  { topic: 'Estacionamiento', difficulty: 'Media', text: 'Está prohibido estacionar, entre otros lugares:', correct: 'En cruces peatonales, frente a hidrantes o donde se obstruya la visibilidad.', wrong: ['Solo dentro de parqueaderos públicos pagos.', 'Únicamente en vías nacionales.', 'Nunca en zona urbana, aunque haya bahía.'], explanation: 'Hay zonas de prohibición expresa por seguridad y acceso de emergencias.' },
  { topic: 'Estacionamiento', difficulty: 'Media', text: 'Al estacionar en pendiente, una buena práctica es:', correct: 'Usar freno de mano y orientar las ruedas de forma segura.', wrong: ['Dejar el vehículo en neutro sin freno de mano.', 'Apagar luces y dejar la puerta abierta sobre el carril.', 'Estacionar ocupando dos carriles “para protegerse”.'], explanation: 'Evita que el vehículo se desplace solo.' },
  { topic: 'Estacionamiento', difficulty: 'Alta', text: 'Doble fila para “bajar un segundo” a un pasajero es:', correct: 'Una infracción que obstruye la circulación.', wrong: ['Permitida menos de 30 segundos.', 'Correcta si enciende direccionales de emergencia.', 'Obligatoria en zonas escolares.'], explanation: 'La doble fila genera congestión y riesgo, aunque sea breve.' },
  { topic: 'Estacionamiento', difficulty: 'Media', text: 'Si no hay cupo legal para estacionar cerca de su destino, usted debe:', correct: 'Buscar un lugar permitido aunque quede más lejos.', wrong: ['Estacionar sobre el andén “un momento”.', 'Dejar el carro en zona amarilla apagando el motor.', 'Bloquear un garaje privado con un mensaje en el parabrisas.'], explanation: 'La falta de cupo no autoriza ocupar espacios prohibidos.' },
  { topic: 'Estacionamiento', difficulty: 'Baja', text: 'Antes de abrir la puerta al estacionar, conviene:', correct: 'Mirar espejos y punto ciego para no golpear ciclistas o motos.', wrong: ['Abrir de un golpe hacia la calzada.', 'Bajar sin mirar si “casi no hay tráfico”.', 'Empujar la puerta con el pie hacia el carril.'], explanation: 'Muchos choques con ciclistas ocurren al abrir puertas sin mirar (efecto puerta).' },

  // Documentos y requisitos
  { topic: 'Documentos y requisitos', difficulty: 'Baja', text: 'Para conducir un vehículo automotor en Colombia usted necesita, entre otros:', correct: 'Licencia de conducción vigente para la categoría correspondiente.', wrong: ['Solo la cédula de ciudadanía.', 'Únicamente el SOAT vencido.', 'Ningún documento si el carro es propio.'], explanation: 'La licencia vigente y adecuada a la categoría es requisito esencial.' },
  { topic: 'Documentos y requisitos', difficulty: 'Media', text: 'El SOAT es:', correct: 'Un seguro obligatorio que cubre daños a personas en accidentes de tránsito.', wrong: ['Un impuesto anual de valorización predial.', 'Un permiso para circular sin licencia.', 'Una póliza opcional solo para carros nuevos.'], explanation: 'El SOAT es obligatorio y protege a las víctimas en accidentes.' },
  { topic: 'Documentos y requisitos', difficulty: 'Media', text: 'Circular con SOAT vencido puede acarrear:', correct: 'Inmovilización y sanciones.', wrong: ['Solo un llamado de atención verbal.', 'Nada, si el vehículo es modelo antiguo.', 'Beneficio de descuento en comparendos.'], explanation: 'Sin SOAT vigente no se puede circular legalmente.' },
  { topic: 'Documentos y requisitos', difficulty: 'Alta', text: 'La revisión técnico-mecánica busca, principalmente:', correct: 'Verificar que el vehículo cumpla condiciones mínimas de seguridad y emisiones.', wrong: ['Cambiar la placa del vehículo cada año.', 'Autorizar el cambio de color sin trámite.', 'Reemplazar la licencia de conducción.'], explanation: 'Evalúa estado mecánico, seguridad y gases según aplique.' },
  { topic: 'Documentos y requisitos', difficulty: 'Media', text: 'Prestar su vehículo a alguien sin licencia válida es:', correct: 'Una conducta riesgosa que puede generar responsabilidad.', wrong: ['Recomendable para que “aprenda en la práctica”.', 'Obligatorio entre familiares.', 'Permitido solo en vías rurales.'], explanation: 'El propietario/conductor debe asegurarse de que quien maneje esté habilitado.' },

  // Alcohol y sustancias
  { topic: 'Alcohol y sustancias', difficulty: 'Alta', text: 'Conducir bajo efectos de alcohol o drogas es:', correct: 'Prohibido y sancionable, con riesgos graves de accidente.', wrong: ['Permitido si se siente “capaz”.', 'Solo falta si hay accidente.', 'Aceptable en trayectos cortos.'], explanation: 'Alcohol y psicoactivos alteran reflejos; la norma los prohíbe al volante.' },
  { topic: 'Alcohol y sustancias', difficulty: 'Media', text: 'Si un agente le solicita prueba de embriaguez, usted debe:', correct: 'Acatar el procedimiento establecido por la autoridad.', wrong: ['Negarse sin consecuencias legales.', 'Huir del control.', 'Ofrecer dinero para evitar la prueba.'], explanation: 'Negarse o evadir controles agrava la situación jurídica.' },
  { topic: 'Alcohol y sustancias', difficulty: 'Alta', text: 'La mejor decisión si bebió alcohol es:', correct: 'No conducir y usar otra alternativa de transporte.', wrong: ['Tomar café y manejar de inmediato.', 'Conducir despacio “para compensar”.', 'Abrir las ventanas para oxigenarse y seguir.'], explanation: 'No hay truco casero que elimine de inmediato la afectación del alcohol.' },
  { topic: 'Alcohol y sustancias', difficulty: 'Media', text: 'Medicamentos que producen sueño o mareo:', correct: 'Pueden incapacitar para conducir; consulte y no maneje si afectan su estado.', wrong: ['Nunca afectan la conducción.', 'Solo importan en carretera.', 'Se compensan subiendo el volumen de la radio.'], explanation: 'Algunos fármacos alteran atención y reflejos igual que el alcohol.' },
  { topic: 'Alcohol y sustancias', difficulty: 'Baja', text: '“Un solo trago no afecta” es una idea:', correct: 'Peligrosa: incluso pequeñas cantidades pueden reducir capacidades.', wrong: ['Siempre cierta para adultos.', 'Válida solo con cerveza.', 'Cierta si se come abundante.'], explanation: 'La afectación varía por persona, pero el riesgo empieza con dosis bajas.' },

  // Seguridad pasiva
  { topic: 'Cinturón y seguridad pasiva', difficulty: 'Baja', text: 'El cinturón de seguridad debe usarse:', correct: 'En todos los asientos ocupados, según la norma y el diseño del vehículo.', wrong: ['Solo en el asiento del conductor.', 'Solo en carretera.', 'Solo si viaja un menor de edad.'], explanation: 'El cinturón salva vidas en ciudad y carretera; no es opcional “porque voy cerca”.' },
  { topic: 'Cinturón y seguridad pasiva', difficulty: 'Media', text: 'Los niños deben viajar:', correct: 'En sistemas de retención infantil adecuados a su edad/talla, en el lugar correcto del vehículo.', wrong: ['En brazos del acompañante en el asiento delantero.', 'De pie entre los asientos traseros.', 'Sin cinturón si el viaje dura menos de 10 minutos.'], explanation: 'La silla o dispositivo infantil reduce lesiones graves en choques.' },
  { topic: 'Cinturón y seguridad pasiva', difficulty: 'Alta', text: 'Un airbag reemplaza el cinturón:', correct: 'Falso: complementa, no sustituye al cinturón.', wrong: ['Verdadero: con airbag no hace falta cinturón.', 'Solo en el asiento trasero.', 'Solo a más de 80 km/h.'], explanation: 'Airbag + cinturón trabajan juntos; sin cinturón el airbag puede incluso lesionar más.' },
  { topic: 'Cinturón y seguridad pasiva', difficulty: 'Media', text: 'Llevar objetos sueltos pesados en la cabina es riesgoso porque:', correct: 'En un frenado o choque se convierten en proyectiles.', wrong: ['Mejoran la estabilidad del vehículo.', 'Están prohibidos solo en buses.', 'No representan peligro a baja velocidad.'], explanation: 'La inercia lanza objetos sueltos con mucha fuerza.' },
  { topic: 'Cinturón y seguridad pasiva', difficulty: 'Baja', text: 'Antes de iniciar la marcha, una verificación básica es:', correct: 'Ajustar asiento, espejos y abrocharse el cinturón.', wrong: ['Revisar solo el claxon.', 'Encender luces altas en ciudad de día.', 'Desactivar el freno de mano después de circular 1 cuadra.'], explanation: 'La preparación del puesto de conducción es el primer acto de seguridad.' },

  // Luces
  { topic: 'Luces y visibilidad', difficulty: 'Media', text: 'Las luces bajas se usan, entre otros casos:', correct: 'De noche en ciudad y cuando hay tráfico en sentido contrario.', wrong: ['Solo en túneles.', 'Nunca de día, aunque llueva.', 'Únicamente con niebla extrema.'], explanation: 'Luces bajas iluminan sin encandilar; son las habituales con tráfico.' },
  { topic: 'Luces y visibilidad', difficulty: 'Alta', text: 'Usar luces altas cuando viene un vehículo de frente es:', correct: 'Incorrecto: debe bajarlas para no encandilar.', wrong: ['Correcto para “hacerse ver mejor”.', 'Obligatorio en toda carretera.', 'Permitido si el otro no baja las suyas.'], explanation: 'Encandilar reduce la visión del otro conductor y aumenta el riesgo.' },
  { topic: 'Luces y visibilidad', difficulty: 'Media', text: 'Las luces direccionales deben usarse:', correct: 'Antes de girar o cambiar de carril, con anticipación suficiente.', wrong: ['Solo después de completar la maniobra.', 'Únicamente en intersecciones con policía.', 'Nunca en parqueaderos.'], explanation: 'La señalización anticipada permite que los demás reaccionen.' },
  { topic: 'Luces y visibilidad', difficulty: 'Media', text: 'En lluvia diurna con poca visibilidad, conviene:', correct: 'Encender luces bajas (y las que la norma/vehículo indiquen) para ser visto.', wrong: ['Apagar todas las luces para no gastar batería.', 'Usar solo exploradoras traseras.', 'Circular sin luces si es de día calendario.'], explanation: 'Ser visible es tan importante como ver.' },
  { topic: 'Luces y visibilidad', difficulty: 'Baja', text: 'Las luces de freno se activan para:', correct: 'Advertir a quienes van atrás que usted está frenando.', wrong: ['Iluminar la vía hacia adelante.', 'Reemplazar las direccionales.', 'Indicar que el vehículo está en reversa.'], explanation: 'Comunican desaceleración a la retaguardia.' },

  // Motos
  { topic: 'Motocicletas', difficulty: 'Media', text: 'El conductor y acompañante de moto deben usar:', correct: 'Casco certificado y abrochado correctamente.', wrong: ['Casco solo en carretera.', 'Gorra deportiva en ciudad.', 'Casco sin abrochar “para ventilación”.'], explanation: 'El casco solo protege si está certificado y bien sujeto.' },
  { topic: 'Motocicletas', difficulty: 'Alta', text: 'Circular en moto entre filas de carros a alta velocidad es:', correct: 'Una práctica peligrosa y muchas veces irregular según el contexto vial.', wrong: ['La forma obligatoria de circular en congestión.', 'Segura si se usa claxon.', 'Recomendada por la norma para fluidificar el tráfico.'], explanation: 'El filtrado imprudente es causa frecuente de choques graves.' },
  { topic: 'Motocicletas', difficulty: 'Media', text: 'Un carro que va a girar debe tener especial cuidado con motos porque:', correct: 'Las motos pueden estar en el punto ciego o adelantar por un costado.', wrong: ['Las motos siempre se detienen solas.', 'Las motos no tienen derecho a circular en ciudad.', 'Solo importan si llevan placa del mismo municipio.'], explanation: 'Verificar espejos y ángulos muertos antes de girar o cambiar de carril.' },
  { topic: 'Motocicletas', difficulty: 'Media', text: 'Llevar un niño pequeño en moto sin las condiciones de seguridad adecuadas es:', correct: 'Riesgoso e irregular según restricciones de edad/condiciones.', wrong: ['Correcto si el niño va al frente del tanque.', 'Permitido solo de día.', 'Seguro con casco de adulto holgado.'], explanation: 'Hay reglas específicas para el transporte de menores en motocicleta.' },
  { topic: 'Motocicletas', difficulty: 'Baja', text: 'Antes de cambiar de carril en moto, el conductor debe:', correct: 'Señalizar y verificar espejos y punto ciego.', wrong: ['Inclinarse sin mirar.', 'Acelerar en seco entre dos vehículos.', 'Confiar solo en el oído.'], explanation: 'La señalización y la verificación visual aplican igual que en automóvil.' },

  // Distancia y frenado
  { topic: 'Distancia y frenado', difficulty: 'Media', text: 'La distancia de seguimiento segura depende de:', correct: 'Velocidad, estado de la vía, clima y tipo de vehículo.', wrong: ['Solo del modelo del vehículo.', 'Únicamente de la hora del día.', 'Nada: siempre basta 1 metro.'], explanation: 'A más velocidad o peor adherencia, más distancia necesita.' },
  { topic: 'Distancia y frenado', difficulty: 'Alta', text: 'Si el vehículo de adelante frena de golpe y usted iba muy cerca:', correct: 'Aumenta la probabilidad de colisión trasera.', wrong: ['No pasa nada si lleva ABS.', 'El de adelante siempre tiene la culpa exclusiva.', 'La distancia corta mejora el tiempo de reacción.'], explanation: 'La colisión trasera suele asociarse a no guardar distancia.' },
  { topic: 'Distancia y frenado', difficulty: 'Media', text: 'En descenso prolongado, lo más adecuado es:', correct: 'Usar marchas cortas/freno motor y no abusar del freno de servicio.', wrong: ['Poner neutro para “ahorrar frenos”.', 'Apagar el motor.', 'Frenar solo al final con el pedal a fondo.'], explanation: 'El freno motor evita sobrecalentar los frenos.' },
  { topic: 'Distancia y frenado', difficulty: 'Media', text: 'Una señal de que está muy cerca del vehículo delantero es:', correct: 'No ver con claridad las ruedas traseras o necesitar frenar con frecuencia brusca.', wrong: ['Ver todo el horizonte por encima de su techo.', 'Poder leer la placa con comodidad y margen.', 'Tener tiempo de conversar mirando el celular.'], explanation: 'Si reacciona tarde ante cada frenada, la distancia es insuficiente.' },
  { topic: 'Distancia y frenado', difficulty: 'Baja', text: 'El ABS ayuda a:', correct: 'Mantener cierto control de dirección al frenar fuerte en muchas condiciones.', wrong: ['Aumentar la velocidad máxima legal.', 'Eliminar por completo la distancia de frenado.', 'Permitir no usar cinturón.'], explanation: 'ABS evita el bloqueo total de ruedas; no sustituye distancia ni atención.' },

  // Señales y marcas (comportamiento)
  { topic: 'Señales y marcas viales', difficulty: 'Media', text: 'Una línea longitudinal continua amarilla en el centro generalmente indica:', correct: 'No adelantar / no invadir el sentido contrario.', wrong: ['Carril exclusivo de buses.', 'Zona de estacionamiento permitido.', 'Inicio de vía peatonal.'], explanation: 'La continua separa sentidos y restringe adelantamientos.' },
  { topic: 'Señales y marcas viales', difficulty: 'Media', text: 'Una línea discontinua suele permitir:', correct: 'Adelantar o cambiar de carril cuando sea seguro y no haya otra restricción.', wrong: ['Estacionar sobre la línea.', 'Circular en sentido contrario libremente.', 'Ignorar semáforos cercanos.'], explanation: 'La discontinua marca separación con posibilidad de cruzarla con precaución.' },
  { topic: 'Señales y marcas viales', difficulty: 'Baja', text: 'Las señales preventivas (por ejemplo, curva peligrosa) sirven para:', correct: 'Advertir un peligro o situación especial en la vía.', wrong: ['Imponer una sanción inmediata al verlas.', 'Indicar el nombre de municipios únicamente.', 'Autorizar exceso de velocidad.'], explanation: 'Preventivas alertan; reglamentarias ordenan o prohíben.' },
  { topic: 'Señales y marcas viales', difficulty: 'Alta', text: 'Si hay conflicto aparente entre un semáforo en verde y un agente de tránsito que detiene el flujo, usted debe:', correct: 'Obedecer al agente de tránsito.', wrong: ['Obedecer solo al semáforo.', 'Hacer lo que haga el vehículo de al lado.', 'Acelerar antes de que el agente lo vea.'], explanation: 'La autoridad en el sitio prevalece sobre la señal automática.' },
  { topic: 'Señales y marcas viales', difficulty: 'Media', text: 'Pintura de “cebra” peatonal indica:', correct: 'Zona donde los peatones cruzan y el conductor debe cederles el paso.', wrong: ['Carril preferente para motos.', 'Área de estacionamiento corto.', 'Pista de aceleración.'], explanation: 'Es un cruce peatonal marcado.' },

  // Incidentes
  { topic: 'Accidentes e incidentes', difficulty: 'Alta', text: 'Si presencia un accidente con heridos, lo primero es:', correct: 'Asegurar la escena (señalizar) y pedir ayuda / emergencias, sin agravar lesiones.', wrong: ['Mover siempre al herido de inmediato sin evaluar.', 'Irse para “no involucrarse”.', 'Grabar redes antes de auxiliar.'], explanation: 'Prioridad: no generar otro choque y activar ayuda profesional.' },
  { topic: 'Accidentes e incidentes', difficulty: 'Media', text: 'En un choque solo materiales sin heridos, una conducta correcta es:', correct: 'No obstruir innecesariamente, documentar y seguir el procedimiento legal/asegurador.', wrong: ['Abandonar el lugar sin datos.', 'Agredir al otro conductor.', 'Bloquear ambos sentidos “hasta aclarar todo” durante horas si se puede retirar.'], explanation: 'Hay que facilitar el tráfico y cumplir deberes legales y de seguro.' },
  { topic: 'Accidentes e incidentes', difficulty: 'Media', text: 'Huirse después de un accidente es:', correct: 'Una falta grave (fuga) con consecuencias penales/administrativas.', wrong: ['Aceptable si el otro tuvo la culpa.', 'Correcto si no hay testigos.', 'Solo importa en accidentes con muertos.'], explanation: 'La fuga agrava la situación jurídica del conductor.' },
  { topic: 'Accidentes e incidentes', difficulty: 'Alta', text: 'El triángulo o dispositivos de alerta se usan para:', correct: 'Advertir a otros conductores sobre un vehículo detenido o peligro en la vía.', wrong: ['Decorar el maletero.', 'Sustituir las luces de freno en marcha.', 'Señalizar un estacionamiento residencial permanente.'], explanation: 'La señalización del incidente evita choques en cadena.' },
  { topic: 'Accidentes e incidentes', difficulty: 'Baja', text: 'El número de emergencias en Colombia para accidentes suele incluir:', correct: 'Líneas de emergencia (p. ej. 123) según el municipio/servicio.', wrong: ['Solo redes sociales del CEA.', 'El número de la emisora favorita.', 'Ninguno: debe esperarse a un transeúnte.'], explanation: 'Activar el sistema de emergencias es parte de la respuesta correcta.' },

  // Comportamiento y civismo
  { topic: 'Comportamiento vial', difficulty: 'Media', text: 'Usar el celular en la mano mientras conduce es:', correct: 'Peligroso y sancionable.', wrong: ['Permitido en semáforo en rojo.', 'Correcto con una sola mano al volante.', 'Obligatorio para reportar tráfico.'], explanation: 'La distracción por celular es causa mayor de accidentes.' },
  { topic: 'Comportamiento vial', difficulty: 'Baja', text: 'El claxon debe usarse para:', correct: 'Advertir un peligro real, no para expresar ira.', wrong: ['Saludar en cada esquina.', 'Presionar al de adelante en cada semáforo.', 'Sustituir las direccionales.'], explanation: 'El claxon es dispositivo de alerta, no de agresión.' },
  { topic: 'Comportamiento vial', difficulty: 'Media', text: 'Conducir con fatiga extrema aumenta el riesgo porque:', correct: 'Disminuye atención y reflejos, similar a conducir alcoholizado en cierto grado.', wrong: ['Mejora la concentración por “adrenalina”.', 'No tiene efecto en trayectos cortos.', 'Solo afecta a conductores novatos.'], explanation: 'El cansancio mata; hay que descansar o no manejar.' },
  { topic: 'Comportamiento vial', difficulty: 'Alta', text: 'Una “racha” o competencia de velocidad en vía pública es:', correct: 'Ilegal y extremadamente peligrosa.', wrong: ['Deporte urbano permitido de noche.', 'Falta leve sin sanción.', 'Permitida en avenidas de tres carriles.'], explanation: 'Las piques callejeros ponen en riesgo a terceros inocentes.' },
  { topic: 'Comportamiento vial', difficulty: 'Media', text: 'Respetar al otro conductor implica, entre otras cosas:', correct: 'No cerrarle el paso ni realizar maniobras de intimidación.', wrong: ['Obligarlo a apartarse tocando el claxon sin motivo.', 'Seguirlo hasta su casa tras un roce.', 'Grabarlo para insultarlo en redes mientras maneja.'], explanation: 'La convivencia vial exige autocontrol y respeto.' },

  // Carga y dimensiones
  { topic: 'Carga y ocupantes', difficulty: 'Media', text: 'Transportar carga que sobresale sin señalizar adecuadamente es:', correct: 'Riesgoso e irregular.', wrong: ['Correcto si va a menos de 40 km/h.', 'Permitido solo de día sin ninguna marca.', 'Obligatorio en camionetas.'], explanation: 'La carga debe ir asegurada y señalizada cuando sobresale.' },
  { topic: 'Carga y ocupantes', difficulty: 'Alta', text: 'Llevar más pasajeros que los cupos del vehículo es:', correct: 'Una infracción que además reduce la seguridad.', wrong: ['Correcto en trayectos escolares cortos.', 'Permitido si todos llevan cinturón improvisado.', 'Solo falta en carreteras nacionales.'], explanation: 'El número de plazas está limitado por diseño y norma.' },
  { topic: 'Carga y ocupantes', difficulty: 'Media', text: 'Un animal suelto en la cabina mientras conduce:', correct: 'Puede distraer y provocar un accidente; debe ir asegurado/condicionado.', wrong: ['Es la forma más segura de transportarlo.', 'Está prohibido solo en buses.', 'No representa riesgo real.'], explanation: 'Un animal puede interferir con pedales y atención.' },
  { topic: 'Carga y ocupantes', difficulty: 'Baja', text: 'Antes de iniciar un viaje largo con el vehículo cargado, conviene:', correct: 'Revisar presión de llantas, luces, frenos y sujeción de la carga.', wrong: ['Quitar el cinturón para ir más cómodo.', 'Desactivar luces para ahorrar.', 'Ir en neutro en bajadas para ahorrar combustible.'], explanation: 'La revisión pre-viaje evita fallas en ruta.' },
  { topic: 'Carga y ocupantes', difficulty: 'Media', text: 'El maletero o platón sobrecargado por encima de lo permitido:', correct: 'Afecta estabilidad, frenado y puede ser sancionable.', wrong: ['Mejora la tracción siempre.', 'No tiene límite legal.', 'Solo importa la estética.'], explanation: 'El exceso de peso cambia el comportamiento dinámico del vehículo.' },

  // Condiciones especiales
  { topic: 'Condiciones especiales', difficulty: 'Alta', text: 'En niebla densa, lo más seguro es:', correct: 'Reducir velocidad, aumentar distancia y usar luces adecuadas (no altas que reflejen).', wrong: ['Encender solo luces altas fijas.', 'Seguir las luces del de adelante a 1 metro.', 'Detenerse en medio del carril sin señalizar.'], explanation: 'Niebla: ver y ser visto sin encandilar; velocidad acorde a visibilidad.' },
  { topic: 'Condiciones especiales', difficulty: 'Media', text: 'Con piso mojado, la distancia de frenado:', correct: 'Aumenta.', wrong: ['Disminuye a la mitad.', 'No cambia.', 'Solo cambia en vehículos antiguos.'], explanation: 'Menor adherencia = más metros para detenerse.' },
  { topic: 'Condiciones especiales', difficulty: 'Media', text: 'Pasar por un charco profundo a alta velocidad puede causar:', correct: 'Pérdida de control o daño al motor (hidroplaneo / aspiración de agua).', wrong: ['Mejor limpieza del tren delantero sin riesgos.', 'Mayor estabilidad por el peso del agua.', 'Nada relevante.'], explanation: 'Hay que atravesar charcos con precaución y velocidad baja.' },
  { topic: 'Condiciones especiales', difficulty: 'Alta', text: 'Si siente hidroplaneo (el carro “flota”), usted debe:', correct: 'Levantar el pie del acelerador suavemente y no frenar de golpe ni girar brusco.', wrong: ['Girar fuerte hacia la berma.', 'Frenar a fondo de inmediato.', 'Acelerar para “salir del agua”.'], explanation: 'Recuperar tracción requiere suavidad en comandos.' },
  { topic: 'Condiciones especiales', difficulty: 'Baja', text: 'De noche en vía sin iluminación, además de luces correctas, es clave:', correct: 'Reducir velocidad y aumentar atención a peatones y curvas.', wrong: ['Circular a la máxima permitida siempre.', 'Usar solo parking.', 'Confiar 100% en el faro antiniebla trasero.'], explanation: 'La noche reduce información visual; la velocidad debe adecuarse.' },

  // Mecánica básica del conductor
  { topic: 'Revisión del vehículo', difficulty: 'Media', text: 'Una llanta con presión muy baja puede provocar:', correct: 'Mayor consumo, mal agarre y riesgo de reventón o pérdida de control.', wrong: ['Mejor confort sin ningún inconveniente.', 'Frenado más corto siempre.', 'Solo un problema estético.'], explanation: 'La presión correcta es seguridad básica.' },
  { topic: 'Revisión del vehículo', difficulty: 'Baja', text: 'Si el testigo de temperatura del motor se enciende en rojo, usted debe:', correct: 'Detenerse en lugar seguro y no seguir forzando el motor.', wrong: ['Acelerar para refrigerar por velocidad.', 'Ignorarlo hasta llegar a casa a 50 km.', 'Echar agua fría de golpe con el motor al máximo calor sin precaución.'], explanation: 'Seguir con sobrecalentamiento puede destruir el motor y dejarlo varado en peligro.' },
  { topic: 'Revisión del vehículo', difficulty: 'Media', text: 'Limpiaparabrisas en mal estado con lluvia:', correct: 'Reducen visibilidad y deben cambiarse.', wrong: ['No afectan si se usa mucho detergente.', 'Solo importan en carretera.', 'Están prohibidos por norma ambiental.'], explanation: 'Ver bien es condición para conducir seguro.' },
  { topic: 'Revisión del vehículo', difficulty: 'Alta', text: 'Un ruido metálico fuerte al frenar puede indicar:', correct: 'Desgaste o falla en frenos; debe revisarse antes de seguir un viaje exigente.', wrong: ['Que el ABS funciona perfecto siempre.', 'Un problema solo de escape.', 'Nada urgente.'], explanation: 'Los frenos son sistema crítico; los síntomas no se postergan.' },
  { topic: 'Revisión del vehículo', difficulty: 'Media', text: 'Nivel bajo de líquido de frenos es:', correct: 'Una señal de alerta que exige revisión inmediata.', wrong: ['Normal cada semana en todos los carros.', 'Irrelevante si hay ABS.', 'Se soluciona solo con lavar el motor.'], explanation: 'Falta de líquido compromete la capacidad de frenado.' },

  // Normas CEA / examen
  { topic: 'Examen y responsabilidad', difficulty: 'Media', text: 'El objetivo principal de las normas de tránsito es:', correct: 'Proteger la vida e integridad de las personas en la vía.', wrong: ['Recaudar solo multas.', 'Beneficiar únicamente a conductores de carro particular.', 'Eliminar por completo el transporte público.'], explanation: 'La seguridad vial es el fin último del Código.' },
  { topic: 'Examen y responsabilidad', difficulty: 'Baja', text: 'Como futuro conductor CEA, su responsabilidad incluye:', correct: 'Conocer y aplicar normas, y asumir las consecuencias de sus decisiones al volante.', wrong: ['Culpar siempre al peatón.', 'Memorizar solo señales y olvidar la práctica.', 'Conducir solo como le enseñó un familiar, ignore la norma escrita.'], explanation: 'La licencia implica deber legal y ético.' },
  { topic: 'Examen y responsabilidad', difficulty: 'Alta', text: 'Si desconoce una norma en una situación real, lo más seguro es:', correct: 'Optar por la conducta más prudente y ceder el paso si hay duda razonable de prioridad.', wrong: ['Imponerse por velocidad.', 'Seguir a ciegas al vehículo de al lado.', 'Detenerse en cualquier parte del carril sin señalizar.'], explanation: 'Ante la duda, priorice no generar conflicto ni atropello.' },
  { topic: 'Examen y responsabilidad', difficulty: 'Media', text: 'La educación vial continua después de obtener la licencia porque:', correct: 'Las normas, la tecnología y el riesgo en la vía evolucionan; el hábito seguro se mantiene con práctica.', wrong: ['Ya no hay nada que aprender.', 'Solo aplica a conductores de carga pesada.', 'Solo es obligatoria cada 20 años.'], explanation: 'Sacar la licencia es el inicio, no el final del aprendizaje.' },
  { topic: 'Examen y responsabilidad', difficulty: 'Baja', text: 'Una infracción de tránsito puede implicar:', correct: 'Comparendo, sanciones económicas y, en casos graves, suspensión o responsabilidad penal.', wrong: ['Únicamente una sonrisa del agente.', 'Nunca puntos ni consecuencias.', 'Solo aviso por WhatsApp.'], explanation: 'El régimen sancionatorio busca disuadir conductas peligrosas.' },

  // Más cobertura tematica
  { topic: 'Circulación', difficulty: 'Alta', text: 'Invadir el carril contrario en una curva sin visibilidad es:', correct: 'Extremadamente peligroso e incorrecto.', wrong: ['Correcto para “cortar” la curva.', 'Permitido de noche.', 'Recomendado si conoce la vía.'], explanation: 'Puede haber un vehículo de frente; la curva ciega exige mantener su carril.' },
  { topic: 'Velocidad', difficulty: 'Media', text: 'El “mínimo” de velocidad en una vía, cuando está señalizado, existe para:', correct: 'Evitar que vehículos demasiado lentos generen riesgos de colisión y congestión insegura.', wrong: ['Obligar a todos a ir a la máxima.', 'Premiar a quien vaya más despacio siempre.', 'Aplicar solo a motos.'], explanation: 'Circular excesivamente lento también puede ser peligroso cuando hay mínimo señalado.' },
  { topic: 'Prioridad e intersecciones', difficulty: 'Media', text: 'Al girar a la derecha con peatones cruzando a su derecha, usted:', correct: 'Debe ceder el paso a los peatones.', wrong: ['Tiene prioridad absoluta por ir en vehículo.', 'Puede pasar si toca el claxon tres veces.', 'Solo cede si el peatón es adulto mayor.'], explanation: 'El giro no anula el deber de proteger al peatón en el cruce.' },
  { topic: 'Semáforos', difficulty: 'Alta', text: 'Detenerse sobre el cruce peatonal porque “alcanzó a entrar en amarillo” es:', correct: 'Incorrecto: no debe quedar bloqueando el paso de peatones.', wrong: ['Correcto y recomendado.', 'Obligatorio en todas las ciudades.', 'Solo falta si hay cámara.'], explanation: 'La intersección y la cebra deben quedar libres.' },
  { topic: 'Adelantamiento', difficulty: 'Media', text: 'Adelantar a un vehículo que a su vez está adelantando (doble adelantamiento) suele ser:', correct: 'Peligroso e inadecuado en la mayoría de vías de dos sentidos.', wrong: ['La maniobra más eficiente siempre.', 'Obligatorio en congestión.', 'Seguro con luces altas.'], explanation: 'Multiplica ocupación de calzada y reduce márgenes de seguridad.' },
  { topic: 'Estacionamiento', difficulty: 'Alta', text: 'Estacionar en curva pronunciada con poca visibilidad es peligroso porque:', correct: 'Otros no lo ven a tiempo y puede provocar choque.', wrong: ['Mejora la visibilidad del propio conductor.', 'Está siempre permitido con direccionales.', 'Solo es problema de día.'], explanation: 'Las curvas necesitan campo visual libre.' },
  { topic: 'Documentos y requisitos', difficulty: 'Media', text: 'Conducir con licencia de categoría inferior a la del vehículo que opera es:', correct: 'Incorrecto: la categoría debe corresponder al tipo de vehículo.', wrong: ['Correcto si es familiar cercano.', 'Válido los fines de semana.', 'Permitido en el mismo departamento.'], explanation: 'Cada categoría habilita clases específicas de vehículos.' },
  { topic: 'Alcohol y sustancias', difficulty: 'Alta', text: 'El día siguiente de beber en exceso, ¿es seguro asumir que ya puede manejar?', correct: 'No necesariamente: aún puede haber alcohol residual y fatiga.', wrong: ['Sí, siempre al amanecer.', 'Sí, si se duchó.', 'Sí, si desayunó pesado.'], explanation: 'El alcohol no “desaparece” solo porque pasó la noche.' },
  { topic: 'Cinturón y seguridad pasiva', difficulty: 'Media', text: 'Colocar el cinturón debajo del brazo (no sobre el hombro) es:', correct: 'Incorrecto: reduce protección y puede causar lesiones.', wrong: ['Más seguro en choques frontales.', 'Recomendado para embarazadas sin asesoria.', 'Igual de efectivo siempre.'], explanation: 'El cinturón debe ir bien posicionado según el diseño.' },
  { topic: 'Luces y visibilidad', difficulty: 'Media', text: 'Las luces antiniebla se usan principalmente:', correct: 'Cuando la niebla u otra condición reduce mucho la visibilidad, según el diseño del vehículo y la norma.', wrong: ['Siempre de día en ciudad despejada.', 'Para reemplazar direccionales.', 'Solo estéticamente.'], explanation: 'Mal usadas pueden encandilar; bien usadas mejoran ser visto/ver en niebla.' },
  { topic: 'Motocicletas', difficulty: 'Alta', text: 'Un carro que gira a la izquierda debe mirar especialmente motos porque:', correct: 'Pueden acercarse rápido por el carril o punto ciego.', wrong: ['Las motos nunca tienen prioridad.', 'Las motos frenan en menor distancia siempre, sin excepción.', 'No hay riesgo real con motos.'], explanation: 'Muchos choques “izquierda vs moto” ocurren por no verificar.' },
  { topic: 'Distancia y frenado', difficulty: 'Baja', text: 'La regla práctica de “dejar espacio” respecto al de adelante busca:', correct: 'Tener tiempo y distancia para reaccionar.', wrong: ['Molestar a quien quiere adelantar.', 'Cumplir solo una moda de instructores.', 'Aumentar el consumo de combustible a propósito.'], explanation: 'El margen de seguridad es tiempo de reacción + frenado.' },
  { topic: 'Señales y marcas viales', difficulty: 'Media', text: 'Una señal reglamentaria de “velocidad máxima 40” indica:', correct: 'No superar 40 km/h en ese tramo.', wrong: ['Circular exactamente a 40, nunca más lento.', 'Velocidad recomendada solo con lluvia.', 'Límite solo para buses.'], explanation: 'Es un máximo; ir más lento puede ser necesario según condiciones.' },
  { topic: 'Accidentes e incidentes', difficulty: 'Media', text: 'Mover un vehículo accidentado que aún puede rodar, cuando no hay heridos y obstruye, suele hacerse para:', correct: 'Restablecer la circulación y evitar nuevos choques, documentando antes cuando sea posible.', wrong: ['Ocultar evidencias siempre.', 'Evitar llamar al seguro.', 'Dejar el carro cruzado a propósito.'], explanation: 'En choques menores, despejar la vía con prudencia es una práctica segura y ordenada.' },
  { topic: 'Comportamiento vial', difficulty: 'Alta', text: 'Conducir escuchando música a volumen extremo que impide oír ambulancias o cláxones es:', correct: 'Inseguro: reduce la conciencia situacional.', wrong: ['Recomendado para concentrarse.', 'Obligatorio en vías rápidas.', 'Irrelevante para la seguridad.'], explanation: 'El oído también informa del entorno vial.' },
  { topic: 'Condiciones especiales', difficulty: 'Media', text: 'En un túnel, si se detiene el tráfico, usted debe:', correct: 'Mantener calma, distancia, luces adecuadas y no bajarse sin necesidad.', wrong: ['Apagar el motor y dormirse en el carril sin más.', 'Hacer reversa hacia la entrada a alta velocidad.', 'Toclear el claxon sin pausa durante minutos.'], explanation: 'Los túneles requieren disciplina: ventilación, visibilidad y no crear pánico.' },
  { topic: 'Revisión del vehículo', difficulty: 'Baja', text: '¿Cada cuánto conviene revisar visualmente las llantas?', correct: 'Con frecuencia, antes de viajes y al notar anomalías (presión, desgaste, clavos).', wrong: ['Solo cuando revienten.', 'Una vez cada 10 años.', 'Nunca si el carro es nuevo.'], explanation: 'La revisión periódica previene fallas en ruta.' },
  { topic: 'Peatones y actores vulnerables', difficulty: 'Media', text: 'Un adulto mayor cruzando despacio en la cebra requiere que usted:', correct: 'Espere con paciencia hasta que termine de cruzar.', wrong: ['Lo apure con ráfagas de luz.', 'Pase rozándolo.', 'Toque el claxon de forma agresiva.'], explanation: 'La vulnerabilidad exige más tiempo y respeto.' },
  { topic: 'Prioridad e intersecciones', difficulty: 'Alta', text: 'Si dos vehículos llegan casi al mismo tiempo a una intersección sin señales y uno viene por su derecha, usted:', correct: 'Le cede el paso.', wrong: ['Pasa primero porque llegó “un segundo antes” sin certeza.', 'Se detiene en el centro bloqueando.', 'Acelera para ganar el cruce.'], explanation: 'En duda de llegada simultánea, la prioridad de la derecha evita el conflicto.' },
  { topic: 'Velocidad', difficulty: 'Alta', text: 'Reducir de 60 a 50 km/h en zona peatonal densa puede:', correct: 'Bajar mucho la gravedad de un atropello y dar más tiempo de reacción.', wrong: ['No cambiar nada relevante.', 'Aumentar el riesgo siempre.', 'Estar prohibido.'], explanation: 'Pequeñas reducciones de velocidad salvan vidas en atropellos.' },
  { topic: 'Circulación', difficulty: 'Media', text: 'Cambiar de carril sin mirar el punto ciego es peligroso porque:', correct: 'Puede haber una moto o carro justo donde no lo cubre el espejo.', wrong: ['Los espejos laterales lo muestran todo al 100%.', 'El punto ciego no existe en carros modernos.', 'Solo afecta a buses.'], explanation: 'Siempre hay que girar la cabeza / verificar el ángulo muerto.' },
  { topic: 'Documentos y requisitos', difficulty: 'Baja', text: 'El portar los documentos del vehículo (o poder acreditarlos según reglas vigentes) sirve para:', correct: 'Demostrar que el vehículo puede circular legalmente y atender un control.', wrong: ['Decorar la guantera.', 'Evitar usar cinturón.', 'Sustituir la licencia del conductor.'], explanation: 'SOAT, licencia de tránsito y demás soportes acreditan legalidad.' },
  { topic: 'Semáforos', difficulty: 'Media', text: 'Una flecha verde en semáforo suele autorizar:', correct: 'El giro o movimiento indicado por la flecha, con precaución hacia peatones.', wrong: ['Cualquier movimiento en cualquier dirección.', 'Solo estacionar.', 'Circular en rojo del resto de luces hacia donde quiera.'], explanation: 'La flecha es específica para esa trayectoria.' },
  { topic: 'Cinturón y seguridad pasiva', difficulty: 'Alta', text: 'En un choque urbano a 40–50 km/h sin cinturón, el cuerpo:', correct: 'Puede salir disparado contra el tablero/parabrisas con fuerza grave.', wrong: ['Queda quieto por arte de magia.', 'Solo se mueve en choques de carretera.', 'El airbag lo sostiene igual sin cinturón siempre.'], explanation: 'Incluso velocidades “urbanas” generan energías letales sin retención.' },
  { topic: 'Comportamiento vial', difficulty: 'Media', text: 'Si se equivoca de ruta, lo correcto es:', correct: 'Continuar hasta un lugar seguro para corregir, sin giros bruscos ilegales.', wrong: ['Hacer U prohibida inmediata.', 'Detenerse en segundo carril a revisar el celular.', 'Reversa por una avenida.'], explanation: 'Corregir con calma evita infracciones y choques.' },
  { topic: 'Motocicletas', difficulty: 'Media', text: 'El chaleco o prendas reflectivas en moto de noche ayudan a:', correct: 'Ser más visible para otros conductores.', wrong: ['Aumentar la potencia del motor.', 'Evitar el uso de casco.', 'Pagar menos SOAT automáticamente.'], explanation: 'La visibilidad es crítica para motociclistas.' },
  { topic: 'Alcohol y sustancias', difficulty: 'Media', text: 'Ofrecerle el volante a un amigo ebrio “porque él insiste” es:', correct: 'Una mala decisión: no debe conducir en ese estado.', wrong: ['Correcto por solidaridad.', 'Legal si usted va de copiloto atento.', 'Aceptable a pocas cuadras.'], explanation: 'No entregue el control a quien no está en condiciones.' },
  { topic: 'Estacionamiento', difficulty: 'Media', text: 'Dejar el vehículo con el motor encendido y sin conductor en vía pública suele ser:', correct: 'Inseguro e irregular en la mayoría de contextos.', wrong: ['Una práctica recomendada para no gastar batería de arranque.', 'Obligatorio en clima frío.', 'Correcto menos de cinco minutos siempre.'], explanation: 'Vehículo sin control puede moverse o ser hurtado; además puede constituir infracción.' },
  { topic: 'Revisión del vehículo', difficulty: 'Media', text: 'Espejos bien graduados permiten:', correct: 'Ampliar el campo visual y reducir ángulos muertos.', wrong: ['Conducir sin nunca girar la cabeza en ningún caso.', 'Evitar usar direccionales.', 'Circular de noche sin luces.'], explanation: 'Los espejos se ajustan al conductor antes de partir.' },
  { topic: 'Peatones y actores vulnerables', difficulty: 'Alta', text: 'En vías compartidas con ciclorruta adyacente, al girar a la derecha debe:', correct: 'Verificar que no venga un ciclista por la ciclorruta o costado.', wrong: ['Ignorar la ciclorruta porque “no es calzada”.', 'Cerrar el paso al ciclista a propósito.', 'Entrar a la ciclorruta a estacionar.'], explanation: 'Los giros atraviesan trayectorias de ciclistas; hay que mirar antes.' },
  { topic: 'Examen y responsabilidad', difficulty: 'Media', text: 'Aprender normas solo para “pasar el examen” y luego ignorarlas es:', correct: 'Una actitud peligrosa e incorrecta.', wrong: ['El objetivo real del CEA.', 'Aceptable tras el primer año.', 'Requerido por la ley.'], explanation: 'La norma existe para aplicarse en la vía todos los días.' },
  { topic: 'Señales y marcas viales', difficulty: 'Baja', text: 'Una señal de “prohibido estacionar” implica que usted:', correct: 'No debe dejar el vehículo detenido en ese tramo.', wrong: ['Puede estacionar de noche.', 'Puede estacionar con balizas.', 'Puede estacionar si “solo baja a comprar”.'], explanation: 'La prohibición no admite excepciones de conveniencia.' },
  { topic: 'Distancia y frenado', difficulty: 'Alta', text: 'Frenar con el pie en el embrague (en vehículos manuales) de forma habitual:', correct: 'Puede reducir el freno motor y el control; se usa el embrague al final de la detención.', wrong: ['Es la técnica más segura siempre.', 'Aumenta la vida útil del embrague al máximo.', 'Es obligatoria en pendientes.'], explanation: 'El uso correcto del embrague evita desgaste y mejora control.' },
  { topic: 'Velocidad', difficulty: 'Baja', text: 'La velocidad máxima señalizada es:', correct: 'El tope legal en condiciones normales; si hay lluvia o tráfico, puede necesitar ir más lento.', wrong: ['La velocidad a la que debe ir siempre exactamente.', 'Una sugerencia sin valor legal.', 'Solo para conductores novatos.'], explanation: 'Máximo legal ≠ velocidad siempre adecuada.' },
  { topic: 'Circulación', difficulty: 'Media', text: 'Detenerse sobre la vía para discutir con otro conductor es:', correct: 'Peligroso e inadecuado.', wrong: ['La forma correcta de resolver un roce.', 'Obligatorio antes de llamar al seguro.', 'Seguro si enciende balizas en pleno carril rápido.'], explanation: 'Las discusiones se resuelven fuera del flujo, en zona segura.' },
  { topic: 'Accidentes e incidentes', difficulty: 'Alta', text: 'Si atropella a alguien, además de socorrer y avisar a autoridades, usted no debe:', correct: 'Darse a la fuga.', wrong: ['Esperar a la autoridad cuando corresponda.', 'Prestar ayuda humanitaria básica sin agravar lesiones.', 'Facilitar sus datos según el procedimiento.'], explanation: 'La fuga es agravante; la asistencia es un deber.' },
  { topic: 'Luces y visibilidad', difficulty: 'Alta', text: 'Conducir de noche solo con luces de posición (parking) en vía interurbana es:', correct: 'Insuficiente e inseguro/ilegal para circular normalmente.', wrong: ['Lo más recomendado para no gastar bombillos.', 'Correcto si conoce la vía.', 'Permitido sobre 80 km/h.'], explanation: 'Hacen falta luces de circulación adecuadas (bajas/altas según caso).' },
  { topic: 'Comportamiento vial', difficulty: 'Baja', text: 'La paciencia en un tranque es parte de la seguridad porque:', correct: 'Reduce maniobras agresivas y choques por estrés.', wrong: ['No tiene relación con accidentes.', 'Obliga a usar el andén.', 'Permite adelantar por la berma.'], explanation: 'El estrés vial empuja a decisiones peligrosas.' },
  { topic: 'Prioridad e intersecciones', difficulty: 'Baja', text: 'Antes de cruzar una intersección, aunque tenga verde, conviene:', correct: 'Verificar que la vía esté libre de peatones o vehículos rezagados.', wrong: ['Acelerar sin mirar porque el verde “lo cubre todo”.', 'Cerrar los ojos al cruce.', 'Mirar solo el celular del GPS.'], explanation: 'El verde no elimina la necesidad de confirmar que el cruce está despejado.' },
  { topic: 'Documentos y requisitos', difficulty: 'Alta', text: 'Un vehículo con placa adulterada o no visible correctamente puede generar:', correct: 'Inmovilización y sanciones.', wrong: ['Beneficios en peajes.', 'Nada si el SOAT está pago.', 'Permiso especial de circulación.'], explanation: 'La identificación del vehículo debe ser clara y legítima.' },
  { topic: 'Carga y ocupantes', difficulty: 'Alta', text: 'Llevar un pasajero en la tolva (platón) de una camioneta en condiciones no autorizadas es:', correct: 'Peligroso e irregular en la generalidad de casos urbanos.', wrong: ['La forma más segura en ciudad.', 'Permitido si van sentados en el piso.', 'Correcto debajo de 20 km/h siempre.'], explanation: 'Los ocupantes deben ir en plazas diseñadas con retención.' },
  { topic: 'Condiciones especiales', difficulty: 'Alta', text: 'Tras un aguacero, las primeras lluvias suelen ser más resbalosas porque:', correct: 'El agua se mezcla con aceite/polvo acumulado en el asfalto.', wrong: ['El asfalto se vuelve más rugoso.', 'Los frenos mejoran automáticamente.', 'No hay ningún cambio físico.'], explanation: 'La película agua-aceite reduce adherencia al inicio de la lluvia.' },
  { topic: 'Examen y responsabilidad', difficulty: 'Alta', text: 'La mejor forma de demostrar que aprendió a conducir no es memorizar trucos, sino:', correct: 'Tomar decisiones seguras y legales en situaciones reales.', wrong: ['Ir siempre al límite máximo.', 'Imitar a conductores agresivos “con experiencia”.', 'Evitar usar direccionales para no “avisar”.'], explanation: 'Competencia vial = juicio + técnica + respeto a la norma.' },
  { topic: 'Señales y marcas viales', difficulty: 'Alta', text: 'Una zona con marcas de “solo bus” o carril exclusivo implica que usted en automóvil particular:', correct: 'No debe usarlo salvo excepciones expresamente permitidas.', wrong: ['Puede usarlo los domingos libremente siempre.', 'Puede usarlo si va solo.', 'Puede usarlo para adelantar “un momento”.'], explanation: 'Los carriles exclusivos tienen restricción de usuarios.' },
  { topic: 'Motocicletas', difficulty: 'Baja', text: 'Revisar el estado de cadena/kit y frenos en moto es importante porque:', correct: 'Una falla mecánica en moto tiene alto riesgo de caída.', wrong: ['Las motos no requieren mantenimiento.', 'Solo importa la estética del faro.', 'Solo si se compite profesionalmente.'], explanation: 'El mantenimiento preventivo es seguridad.' },
  { topic: 'Alcohol y sustancias', difficulty: 'Baja', text: 'La resaca puede afectar la conducción porque:', correct: 'Deja fatiga, deshidratación y menor concentración.', wrong: ['Mejora los reflejos.', 'No tiene ningún efecto fisiológico.', 'Solo afecta la visión de colores.'], explanation: 'No solo importa el alcoholímetro: el estado general también cuenta.' },
  { topic: 'Estacionamiento', difficulty: 'Baja', text: 'Al salir de un estacionamiento en batería, antes de entrar a la calzada usted:', correct: 'Avanza con precaución y cede a peatones y vehículos con prioridad.', wrong: ['Sale acelerando sin mirar.', 'Sale en reversa a alta velocidad por costumbre.', 'Confía en que “siempre se apartan”.'], explanation: 'La salida de predios exige cesión de paso.' },
  { topic: 'Circulación', difficulty: 'Baja', text: 'Mantener las dos manos al volante (salvo maniobras puntuales) ayuda a:', correct: 'Tener mejor control ante un imprevisto.', wrong: ['Cansar más sin beneficio.', 'Está prohibido por norma.', 'Solo aplica en competencia.'], explanation: 'El control del volante es básico en cualquier emergencia.' },
  { topic: 'Velocidad', difficulty: 'Media', text: 'Entrar a una curva a exceso de velocidad puede provocar:', correct: 'Pérdida de trayectoria o volcamiento.', wrong: ['Mejor estabilidad por fuerza centrífuga “amiga”.', 'Menor desgaste de llantas siempre.', 'Ningún efecto si el carro es automático.'], explanation: 'La velocidad de entrada a curva se elige antes, no en medio.' },
  { topic: 'Semáforos', difficulty: 'Baja', text: 'La luz verde significa:', correct: 'Avanzar si el cruce está despejado y es seguro.', wrong: ['Acelerar al máximo sin mirar.', 'Detenerse siempre.', 'Prioridad para usar el celular.'], explanation: 'Verde autoriza el paso con diligencia, no a ciegas.' },
  { topic: 'Peatones y actores vulnerables', difficulty: 'Baja', text: 'Un peatón ebrio en la calzada:', correct: 'Sigue siendo una persona a proteger; reduzca velocidad y evite el atropello.', wrong: ['Pierde todos los derechos y puede atropellarse sin consecuencia.', 'Debe ser empujado con el vehículo.', 'No requiere precaución especial.'], explanation: 'La vulnerabilidad no se niega por el estado del peatón; usted controla el vehículo.' },
  { topic: 'Documentos y requisitos', difficulty: 'Media', text: 'La licencia vencida:', correct: 'No habilita a conducir; debe renovarse.', wrong: ['Sirve tres meses más automáticamente sin trámite.', 'Solo importa para viajes intermunicipales.', 'Se reemplaza con la cédula.'], explanation: 'Vigencia al día es requisito.' },
  { topic: 'Adelantamiento', difficulty: 'Baja', text: 'Señalizar el adelantamiento sirve para:', correct: 'Informar a los demás su intención y reducir sorpresas.', wrong: ['Decorar el tablero.', 'Asustar al de adelante.', 'Cumplir un requisito solo en examen práctico.'], explanation: 'Sin señal, los otros no pueden anticipar su maniobra.' },
  { topic: 'Revisión del vehículo', difficulty: 'Alta', text: 'Una dirección con holgura excesiva (mucho juego) indica:', correct: 'Riesgo de pérdida de control; debe llevarse a revisión.', wrong: ['Mayor comodidad de manejo urbano.', 'Que el vehículo está “más deportivo”.', 'Un ajuste estético sin seguridad.'], explanation: 'La precisión de la dirección es crítica.' },
  { topic: 'Comportamiento vial', difficulty: 'Media', text: 'Grabar un video para redes mientras maneja con una mano:', correct: 'Es una distracción grave.', wrong: ['Es una habilidad valorada en conductores pro.', 'Está permitido bajo 40 km/h.', 'Solo se prohíbe en buses.'], explanation: 'Si graba, no está atendiendo la vía.' },
  { topic: 'Carga y ocupantes', difficulty: 'Baja', text: 'Asegurar la carga con cinchas o elementos adecuados evita:', correct: 'Que se desplace y cause accidente o caída a la vía.', wrong: ['Que el vehículo consuma menos siempre.', 'La revisión técnico-mecánica.', 'El uso de luces traseras.'], explanation: 'Carga suelta = peligro móvil.' },
  { topic: 'Accidentes e incidentes', difficulty: 'Baja', text: 'El botiquín y extintor en el vehículo, cuando son exigidos/útiles:', correct: 'Forman parte del equipo de seguridad para emergencias.', wrong: ['Solo sirven de adorno.', 'Reemplazan al SOAT.', 'Permiten circular sin frenos.'], explanation: 'Preparación para emergencias reduce daños.' },
  { topic: 'Condiciones especiales', difficulty: 'Baja', text: 'Con sol de frente que encandila, una medida útil es:', correct: 'Reducir velocidad y usar parasol/visera; no improvisar mirando al piso.', wrong: ['Cerrar los ojos un segundo.', 'Acelerar para “pasar rápido el tramo”.', 'Quitarse el cinturón.'], explanation: 'La pérdida temporal de visión exige bajar riesgo inmediato.' },
  { topic: 'Examen y responsabilidad', difficulty: 'Baja', text: 'El instructor o el CEA le enseñan normas para que usted:', correct: 'Las aplique solo al volante, protegiendo vida propia y ajena.', wrong: ['Las ignore cuando “tenga experiencia”.', 'Las use solo para discutir en redes.', 'Las memorice y las olvide el mismo día del examen.'], explanation: 'Formación vial = cambio de conducta permanente.' },
  { topic: 'Señales y marcas viales', difficulty: 'Media', text: 'Una señal de “pare” acompañada de línea de detención indica el lugar donde:', correct: 'Debe quedar detenido el vehículo antes de observar y continuar.', wrong: ['Puede estacionar indefinidamente.', 'Inicia una zona de pico y placa.', 'Termina el SOAT.'], explanation: 'La línea marca el punto de alto.' },
  { topic: 'Prioridad e intersecciones', difficulty: 'Media', text: 'Un vehículo que sale de una gasolinera a la avenida debe:', correct: 'Ceder el paso a quienes circulan por la avenida.', wrong: ['Salir acelerando porque “paga servicio”.', 'Obligar a frenar a todos con el claxon.', 'Usar solo luces altas.'], explanation: 'Incorporación desde predio = ceder.' },
  { topic: 'Luces y visibilidad', difficulty: 'Baja', text: 'Probar luces (altas, bajas, direccionales, freno) periódicamente sirve para:', correct: 'Detectar bombillos fundidos antes de un viaje o control.', wrong: ['Gastar innecesariamente la batería sin beneficio.', 'Evitar usar el cinturón.', 'Aumentar la potencia del motor.'], explanation: 'Luces operativas = comunicación y visión.' },
  { topic: 'Distancia y frenado', difficulty: 'Media', text: 'En congestión tipo “acordeón”, la mejor práctica es:', correct: 'Avanzar suave, mantener margen y evitar frenadas/acelerones extremos.', wrong: ['Pegarse al de adelante para que no se meta nadie.', 'Cambiar de carril cada 5 segundos.', 'Usar el andén.'], explanation: 'La conducción suave reduce choques en cadena.' },
  { topic: 'Motocicletas', difficulty: 'Alta', text: 'Circular en moto sin espejos o con espejos rotos es:', correct: 'Inseguro e irregular: necesita ver lo que ocurre atrás y a los lados.', wrong: ['Estilo libre permitido.', 'Correcto en ciudad.', 'Solo falta en carretera.'], explanation: 'Los espejos son elementos de seguridad obligatorios en la práctica segura y normativa.' },
  { topic: 'Alcohol y sustancias', difficulty: 'Media', text: 'Combinar alcohol con medicamentos depresores del sistema nervioso:', correct: 'Puede potenciar la somnolencia y el peligro al conducir.', wrong: ['Se anulan entre sí.', 'Es recomendable para relajarse antes de manejar.', 'No tiene interacción posible.'], explanation: 'Las combinaciones pueden ser más peligrosas que cada sustancia sola.' },
  { topic: 'Circulación', difficulty: 'Alta', text: 'En una vía con sentido único, circular en sentido contrario es:', correct: 'Una infracción grave y muy peligrosa.', wrong: ['Permitido “un tramo cortico”.', 'Correcto si no hay cámaras.', 'Aceptable de madrugada.'], explanation: 'El sentido vial existe para evitar choques frontales.' },
  { topic: 'Velocidad', difficulty: 'Media', text: 'El exceso de velocidad en zona residencial es especialmente grave porque:', correct: 'Hay más peatones, niños y accesos vehiculares impredecibles.', wrong: ['No hay riesgo real en barrios.', 'Los límites solo aplican a avenidas.', 'Los residentes tienen prioridad para ir rápido.'], explanation: 'El entorno residencial exige más cautela.' },
  { topic: 'Estacionamiento', difficulty: 'Alta', text: 'Ocupar el acceso de un garaje ajeno “mientras hace un mandado” es:', correct: 'Incorrecto: obstruye un acceso y puede ser sancionable.', wrong: ['Un derecho del conductor visitante.', 'Permitido con balizas.', 'Correcto menos de dos minutos siempre.'], explanation: 'No se pueden bloquear accesos de terceros.' },
  { topic: 'Comportamiento vial', difficulty: 'Alta', text: 'Perseguir a otro vehículo por una ofensa de tránsito para “ajustarle cuentas” es:', correct: 'Conducta peligrosa e ilegal (agresividad vial).', wrong: ['Justicia privada aceptada.', 'Recomendada por algunos foros.', 'Obligatoria si le cerraron el paso.'], explanation: 'No se responde la agresividad con más riesgo.' },
  { topic: 'Accidentes e incidentes', difficulty: 'Media', text: 'Tomar fotos del accidente sirve si:', correct: 'Se hace sin ponerse en peligro ni obstaculizar emergencias, para documentar.', wrong: ['Es lo único que importa, antes que auxiliar heridos.', 'Se hace desde el centro del carril rápido sin chaleco ni señalizar.', 'Reemplaza denunciar o avisar a autoridades cuando hay deber de hacerlo.'], explanation: 'Documentar ayuda al seguro, pero no está por encima de la vida ni la seguridad de la escena.' },
  { topic: 'Documentos y requisitos', difficulty: 'Baja', text: 'Verificar la fecha de vencimiento del SOAT antes de un viaje largo es:', correct: 'Una práctica responsable.', wrong: ['Innecesaria si el carro enciende.', 'Solo para carros de empresa.', 'Un mito de instructores.'], explanation: 'Evita imprevistos legales y de cobertura en ruta.' },
  { topic: 'Peatones y actores vulnerables', difficulty: 'Media', text: 'Las personas con movilidad reducida en la vía requieren:', correct: 'Mayor tiempo y espacio; no se les hostiga.', wrong: ['Que se aparten al oír un claxon largo.', 'Menos derechos que un conductor con prisa.', 'Usar siempre la calzada central.'], explanation: 'La inclusión vial es parte de la seguridad y la dignidad.' },
  { topic: 'Semáforos', difficulty: 'Alta', text: 'Si va a girar en “verde” pero un peatón inicia el cruce legalmente, usted:', correct: 'Espera a que el peatón termine.', wrong: ['Lo obliga a devolverse.', 'Pasa rozando para “enseñar”.', 'Toca el claxon hasta que corra.'], explanation: 'El peatón en cruce tiene prioridad práctica y legal de protección.' },
  { topic: 'Revisión del vehículo', difficulty: 'Media', text: 'Un humo azul excesivo por el escape puede indicar:', correct: 'Consumo de aceite / problema de motor que merece diagnóstico.', wrong: ['Que el combustible es de mejor calidad.', 'Un ajuste normal tras cada lavada.', 'Nada relacionado con el motor.'], explanation: 'El color del humo da pistas de fallas; no se ignora.' },
  { topic: 'Examen y responsabilidad', difficulty: 'Media', text: 'Cuando obtenga la licencia, usted representa también a:', correct: 'Una cultura vial: sus actos influyen en la seguridad de todos.', wrong: ['Solo a sí mismo, sin impacto social.', 'Únicamente a su familia.', 'Al fabricante del vehículo nada más.'], explanation: 'Conducir es un acto social con externalidades de riesgo.' }
];

function mulberry32(a) {
  return function () {
    let t = (a += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffle(arr, rand) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function build() {
  const all = [...RAW, ...EXTRA];
  const questions = all.map((q, index) => {
    const rand = mulberry32(1000 + index * 97);
    // A veces alargar una incorrecta para que la correcta no sea la más larga.
    const wrongs = q.wrong.map((w, wi) => {
      if (wi === index % 3 && w.length < q.correct.length + 10) {
        return `${w} Además, esa idea no está respaldada por la norma aplicable.`;
      }
      return w;
    });
    let options = [
      { text: q.correct, isCorrect: true },
      { text: wrongs[0], isCorrect: false },
      { text: wrongs[1], isCorrect: false },
      { text: wrongs[2], isCorrect: false }
    ];
    options = shuffle(options, rand);
    // Forzar distribución: si por azar muchas correctas caen en el mismo slot, rotar.
    const preferSlot = index % 4;
    const correctIdx = options.findIndex((o) => o.isCorrect);
    if (correctIdx !== preferSlot) {
      const tmp = options[preferSlot];
      options[preferSlot] = options[correctIdx];
      options[correctIdx] = tmp;
    }
    return {
      subject: 'Normas de tránsito',
      topic: q.topic,
      subtopic: q.topic,
      difficulty: q.difficulty,
      type: 'Seleccion multiple',
      text: q.text,
      explanation: q.explanation,
      source: q.source || 'Ley 769 de 2002 — Código Nacional de Tránsito; buenas prácticas CEA',
      options
    };
  });

  // Validaciones de calidad
  const pos = [0, 0, 0, 0];
  let correctLongest = 0;
  for (const q of questions) {
    const ci = q.options.findIndex((o) => o.isCorrect);
    pos[ci]++;
    const lengths = q.options.map((o) => o.text.length);
    const max = Math.max(...lengths);
    if (q.options[ci].text.length === max) correctLongest++;
  }

  const payload = {
    bankName: 'Normas de tránsito (Colombia)',
    description:
      'Banco CEA v2.1: preguntas originales de normas (Ley 769). Respuesta correcta con posición y longitud variables.',
    blockName: 'Normas de tránsito',
    replaceExisting: true,
    questions
  };

  fs.writeFileSync(OUT, JSON.stringify(payload, null, 2), 'utf8');
  console.log('Wrote', OUT);
  console.log('Questions:', questions.length, `(base ${RAW.length} + extra ${EXTRA.length})`);
  console.log('Correct position counts [A,B,C,D]:', pos);
  console.log('Correct is longest:', correctLongest, '/', questions.length);
}

build();
